### ISSUE TITLE
Convert to HTML without list animation

### ISSUE THREAD

**Issue by iroychoudhury** [marp-team/marp-cli#102]
Hello @yhatt,

Could it be possible to provide a flag to stop the one-by-one appearance of bullets/lists in html format? I basically want to have my entire list appear at once without having to press 'next' multiple times. 

Thanks!

**Comment by yhatt** [comment]
Just replace the bullet `*` into `-` in list item, and `1)` into `1.` in ordered list. Or would you have some reason why could not replace?

**Comment by iroychoudhury** [comment]
No, that would be fine. Thank you for this!
