### ISSUE TITLE
Failed to find `.md` file in non-ASCII directory

### ISSUE THREAD

**Issue by saiya** [marp-team/marp-cli#108]
marp-cli failed to glob markdown files within non-ASCII directory. Thus `marp --server .` exits.

# Way to reproduce

```
% grep marp-cli yarn.lock 
"@marp-team/marp-cli@^0.10.0":
  resolved "https://registry.yarnpkg.com/@marp-team/marp-cli/-/marp-cli-0.10.2.tgz#111be76a2df5f3c228f08dc3627eadbe23fbf3e8"

% pwd
/Users/seiya.yazaki/work/github.com/saiya/presentations/190913 RDBMS 実践
# ↑ It contains non-ASCII character in directory name

% ls *.md
-rw-r--r-- 1 seiya.yazaki staff 1.6K  6 24 15:07  slide.md

% yarn marp --server .
yarn run v1.17.0
$ '/Users/seiya.yazaki/work/github.com/saiya/presentations/190913 RDBMS 実践/node_modules/.bin/marp' --server .
Usage:
  marp [options] <files...>
  marp [options] -I <dir>

Basic Options:
  --version, -v      Show versions                                        [真偽]
  --help, -h         Show help                                            [真偽]
    .... snip ....
```

# Expected result

`yarn marp --server .` should start server, not showing help.

# Workaround 

Use ASCII directory name:

```
% pwd
/Users/seiya.yazaki/work/github.com/saiya/presentations/190913 RDBMS Advanced

% ls *.md
-rw-r--r-- 1 seiya.yazaki staff 1.6K  6 24 15:07  slide.md

% yarn marp --server .
yarn run v1.17.0
$ '/Users/seiya.yazaki/work/github.com/saiya/presentations/190913 RDBMS Advanced/node_modules/.bin/marp' --server .
[  INFO ] [Server mode] Start server listened at http://localhost:8080/ ...
```

**Comment by saiya** [comment]
I debugged marp-cli and found that `globby` returns empty list when I use non-ASCII directory name: https://github.com/marp-team/marp-cli/blob/v0.10.2/src/file.ts#L122

But it is hard for me to debug why `globby` fails to find markdown files...

**Comment by yhatt** [comment]
The cause is very similar to #95 I'm found.

**Comment by yhatt** [comment]
It might cause in the upstream package [`fast-glob`](https://github.com/mrmlnc/fast-glob) v2.2.7. The latest [v3](https://github.com/mrmlnc/fast-glob/releases/tag/3.0.0) has already fixed this.

```
.
├── test.js
├── a
│   └── test
└── 字
    └── test
```

```
// test.js
const fastGlob = require('fast-glob')

// Globby calls fast-glob internally with the path like these
for (const path of ['a/**/*', '字/**/*']) {
  console.log(path, fastGlob.sync(path))
}
```

```bash
# fast-glob v2.2.7
$ node test.js
a/**/* [ 'a/test' ]
字/**/* []

# fast-glob v3.0.2
$ node test.js
a/**/* [ 'a/test' ]
字/**/* [ '字/test' ]
```

**Comment by yhatt** [comment]
@saiya I've created PR #109 with updated fast-glob. Could you try to build Marp CLI and test non-ASCII directory on [`glob-non-ascii-dir`](https://github.com/marp-team/marp-cli/tree/glob-non-ascii-dir) branch?

**Comment by saiya** [comment]
@yhatt Thank you. [glob-non-ascii-dir](https://github.com/marp-team/marp-cli/tree/glob-non-ascii-dir) works well with non-ASCII directory in my environment also.

I will wait for globby's update as you posted.

**Comment by yhatt** [comment]
I worked for getting fast-glob v3 in globby, and it came as globby v10 :satisfied:
https://github.com/sindresorhus/globby/releases/tag/v10.0.0
