### ISSUE TITLE
Watch mode does not work

### ISSUE THREAD

**Issue by meganehouser** [marp-team/marp-cli#134]
When marp-cli was executed in watch mode, an error was output and stopped.
I use macOS Mojave (10.14.6)

```
% npx @marp-team/marp-cli -w slides.md 
[  INFO ] Converting 1 markdown...
[ ERROR ] Failed converting Markdown. (Provided options.stopPort(40000is less than options.startPort (52000))
```

**Comment by yhatt** [comment]
It comes from unintended breaking by patch update of `portfinder` (https://github.com/http-party/node-portfinder/issues/85). Marp CLI uses port 52000 resolved by portfinder to send reload signal to watched HTML.

We can wait for a patch working at http-party/node-portfinder#86 in progress, or change default port number to under 40000.

**Comment by yhatt** [comment]
The latest `portfinder` was temporally rolled back to worked version. `npx @marp-team/marp-cli -w` should work now.
https://github.com/http-party/node-portfinder/pull/86#issuecomment-522739507
