### ISSUE TITLE
Can marpcli's server render user's local images?

### ISSUE THREAD

**Issue by Ganariya** [marp-team/marp-cli#163]
Hello.
I'm ganariya who studies in Akita University.

I'd like to use marp-cli to make a slide by markdown.
And I tired to use image syntax

![](/Users/ganariya/Desktop/Marp_CLI/images/image.png)

But, If I use 

```
marp --html --server --watch --allow-local-files
```

above server funtion, image cannot reveal.

However, If I export pdf, I can see image on the pdf.

Can marp-cli's server render user's local images?

Thank you.

**Comment by yhatt** [comment]
Yes. In server mode, you can use local image files have placed at the served directory and subdirectories.

For example, `image.png` placed in `foobar` directory can use with below.

```
marp --html --server ./foobar
```

```markdown
<!-- foobar/index.md -->
![](image.png)
```

**Comment by Ganariya** [comment]
Thank you for your answer.
When I replaced images directory to markdown sub directory, I can see the image in server mode.

Could I ask you another question?
![](./images/1.png) this code can make image on the server mode.
But
![30%](./images/1.png)  doesn't make sense, so the image size doesn't change.

However, ![bg 30%](./images/1.png)  can reduce the size .

Is this a bug?

Thank you.

**Comment by yhatt** [comment]
It's not a bug. In Marp Next, the inline image has to resize with `width:XXXpx` or `height:XXXpx`.

Please read [the document of Marpit framework](https://marpit.marp.app/image-syntax?id=resizing-image). All syntaxes for image are listed to that.

> NOTICE: Keep in mind that GitHub issue tracker is not a support forum. Please read [our contribution guide](https://github.com/marp-team/marp/blob/master/.github/CONTRIBUTING.md#question). (An one issue should have only one theme / Stackoverflow is the best place for question)
