### ISSUE TITLE
PDF renders do not include the mounted CSS themes or background images.

### ISSUE THREAD

**Issue by spkane** [marp-team/marp-cli#165]
The current release no longer renders an external CSS theme properly. I am not sure when this broke, but I'd guess sometime in the last few months.

It is possible that  Puppeter and Chromium are out of sync again in `marp-cli`, but the last time that happened the rendering completely hung. The initial time this happened was here: https://github.com/marp-team/marp-cli/issues/73

**Comment by yhatt** [comment]
I've tried to reproduce but cannot confirm reported problem. Would you provide details how to reproduce?

**Comment by spkane** [comment]
So, I archived a known working version of the container awhile ago that I believe was built from git SHA: `3fe441cf7a406416300735b0f5de4a6e48a6ff69`

When I convert using that older container (from 10 months ago or so) using `docker run --rm -v $PWD:/home/marp/app/ spkane/marp-cli:working target.md --theme-set spkane.css --pdf --allow-local-files` everything works fine.

![image](https://user-images.githubusercontent.com/129629/65920826-14cb2280-e395-11e9-9bca-cae2442f2e98.png)

If I run the same command with the current image, I end up with no background image in my PDFs and the CSS themes looks generally incorrect (so likely the default).

`docker run --rm -v $PWD:/home/marp/app/ marpteam/marp-cli:latest target.md --theme-set spkane.css --pdf --allow-local-files`

![image](https://user-images.githubusercontent.com/129629/65920885-3debb300-e395-11e9-893b-10a90733ac53.png)

If you want to get your hands on the CSS, etc I can likely make a test project out of it, but I don't believe it is directly related to the CSS/images, although I suppose it could be.

**Comment by yhatt** [comment]
At a glance, it looks like that custom CSS theme cannot be loaded correctly. Let me take a time to find a cause...

**Comment by spkane** [comment]
Is there a way that I can turn up the logging to see if there are any actual errors generated?

**Comment by yhatt** [comment]
For now, an only way is checking `[ ERROR ]` output. But this case is seems not to throw error.

I've tried some cases but cannot reproduce reported problem yet. Some hints I can provide at the moment:

- Try `--theme` option instead of `--theme-set`, for setting theme forcely.
- If you are setting theme in Markdown through `$theme` directive, replace to `theme`. [Dollar prefix support was removed](https://github.com/marp-team/marpit/issues/182) since Marp CLI v0.14.0. ([Marpit v1.4.0](https://github.com/marp-team/marpit/releases/tag/v1.4.0)).

**Comment by spkane** [comment]
It looks like replacing:

`<!-- $theme: spkane -->`

with:

`<!-- theme: spkane -->`

did the trick. 

Thank you for the pointer to that. It might be nice to detect the use of the older dollar prefixes and report a warning when they are encountered.

**Comment by spkane** [comment]
Feature request here: https://github.com/marp-team/marp-cli/issues/193
