### ISSUE TITLE
`--engine @marp-team/marpit` doesn't work well

### ISSUE THREAD

**Issue by exKAZUu** [marp-team/marp-cli#167]
https://github.com/marp-team/marp-cli#zero-js-slide-deck and https://github.com/marp-team/marp-cli#use-marpit-framework use the engine option `--engine @marp-team/marpit`, but this option makes the background color black (font color is also black, so texts cannot be seen.)

I confirm `--engine @marp-team/marp-core` works well. So I think we should fix the doc.

**Comment by exKAZUu** [comment]
I found the default option uses `@marp-team/marp-core` (c.f. https://github.com/marp-team/marp-cli/blob/master/src/config.ts).

**Comment by yhatt** [comment]
It's expected behavior. It's expected behavior. *Marpit does not provide theme* so you should use  theme CSS for getting correct rendering.

> Notice that Marpit has not provided theme. It would be good to include inline style in Markdown, or pass CSS file by --theme option.
>
> *–– https://github.com/marp-team/marp-cli#use-marpit-framework*

**Comment by exKAZUu** [comment]
I see, thanks.
