### ISSUE TITLE
`--engine ./engine.js` doesn't render code blocks well

### ISSUE THREAD

**Issue by exKAZUu** [marp-team/marp-cli#168]
I have the following files.

- engine.js
   ```
   const { Marp } = require('@marp-team/marp-core');
   module.exports = opts => new Marp(opts);
   ```

   Note: I've also tested `module.exports = opts => new Marp();`, but there seems no difference.

- sample.md
   ```
   # test
   
   ` ` ` <- We cannot use triple backquoations in clode blocks so I use ` ` ` here instead
   console.log('Hello World!');
   ` ` `
   ```

- package.json
   ```
   ...
   "devDependencies": {
     "@marp-team/marp-cli": "0.14.1",
     "@marp-team/marp-core": "0.13.1",
     "@marp-team/marpit": "1.4.0",
   ...
   ```

When I use ` --engine @marp-team/marp-core`, it works well.
Interestingly, when I use ` --engine ./engine.js`, it doesn't render the code block well as follows.

![image](https://user-images.githubusercontent.com/436237/66186088-448f6880-e6bc-11e9-95e2-f81baa9be637.png)

**Comment by exKAZUu** [comment]
I upload the generated html file as `.txt` file here.

[sample.html.txt](https://github.com/marp-team/marp-cli/files/3689248/sample.html.txt)

**Comment by yhatt** [comment]
Thanks for feedback. Perhaps it's not triggered [`Marp.ready()`](https://github.com/marp-team/marp-core#marpready) on the browser context.

Marp Core package has [defined path to JS for bundling with HTML](https://github.com/marp-team/marp-core/blob/master/package.json#L29), but it's cannot in functional engine. We should consider a way to add browser script by custom engine.

As a workaround, load Marp Core's browser script manually in Markdown. (require `--html` option)

```markdown
# Your contents

...

<script defer src="https://cdn.jsdelivr.net/npm/@marp-team/marp-core/lib/browser.js"></script>
```

**Comment by exKAZUu** [comment]
Thank you for your quick response. I confirm the workaround solves this issue!
