### ISSUE TITLE
How to enable auto-scaling for code on a slide?

### ISSUE THREAD

**Issue by opdavies** [marp-team/marp-cli#187]
Is there a way of enabling auto-scaling for code within markdown slides? I've tried a couple of things, but none seem to work. I'm using the default theme.

**Comment by yhatt** [comment]
Seemingly I can be interpreted that it's resolved from closing. FYI default theme has [already enabled auto-scaling](https://github.com/marp-team/marp-core/blob/master/themes/default.scss#L7) for code so you should see auto-scaled code block without doing any extra thing.
