### ISSUE TITLE
Preview Error: Unknown permission type: clipboardRead

### ISSUE THREAD

**Issue by zhaozhiming** [marp-team/marp-cli#190]
Hi, I have trouble with marp. It works fine last week, but it throw errors as follows this week. Please help. Thanks.

My env info:
npm: 6.9.0
node: 10.16.0
marp-cli: @marp-team/marp-cli v0.16.2 (w/ @marp-team/marp-core v0.15.2)
browser: Chrome canary Version 81.0.3991.0 (Official Build) canary (64-bit)

```js 
npx @marp-team/marp-cli foo.md --preview
[  INFO ] Converting 1 markdown...
[  INFO ] foo.md => foo.html
[  INFO ] [Watch mode] Start watching...
[  INFO ] [Preview] (EXPERIMENTAL) Opening
          file:///Users/zhaozhiming/Documents/foo...
(node:36765) UnhandledPromiseRejectionWarning: Error: Protocol error (Browser.grantPermissions): Unknown permission type: clipboardRead
.......
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:36985) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:36985) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

**Comment by yhatt** [comment]
Probably [current Puppeteer's overridden permissions](https://github.com/puppeteer/puppeteer/blob/511dcf9d32638c8b6166dad90b11d432e79f2dd2/lib/Browser.js#L344) are not yet supported available permissions in the latest Chrome Canary (`clipboardRead` permission might be removed in 81).

Would you like to try using stable Chrome 79? You can specify executable Chrome via `CHROME_PATH` env.

```bash
CHROME_PATH=/usr/bin/google-chrome npx @marp-team/marp-cli foo.md --preview
```

**Comment by zhaozhiming** [comment]
I try to add `CHROME_PATH=/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome` before `npx @marp-team/marp-cli foo.md --preview` and it works fine. Thanks.

**Comment by aman-primelab** [comment]
> Probably [current Puppeteer's overridden permissions](https://github.com/puppeteer/puppeteer/blob/511dcf9d32638c8b6166dad90b11d432e79f2dd2/lib/Browser.js#L344) are not yet supported available permissions in the latest Chrome Canary (`clipboardRead` permission might be removed in 81. [Playwright](https://github.com/microsoft/playwright), the new generation library for general browsers, is using [`clipboardReadWrite` instead](https://github.com/microsoft/playwright/blob/5b4d32d375a181f3742df950edc8a77411b8f780/src/chromium/crBrowser.ts#L354)).
> 
> Would you like to try using stable Chrome 79? You can specify executable Chrome via `CHROME_PATH` env.
> 
> ```shell
> CHROME_PATH=/usr/bin/google-chrome npx @marp-team/marp-cli foo.md --preview
> ```

It worked for me
