### ISSUE TITLE
[Feature Request] Print a warning when the system detects the older dollar prefixes.

### ISSUE THREAD

**Issue by spkane** [marp-team/marp-cli#193]
It would be nice if `marp-cli` would print a warning when the system detects the older dollar prefixes.

Related: https://github.com/marp-team/marp-cli/issues/165

**Comment by yhatt** [comment]
We've already outputted deprecation warning about dollar prefix for about a month. (Marp CLI [v0.13.x](https://github.com/marp-team/marp-cli/releases/tag/v0.13.0)) We think Marp CLI had enough time for migration.

We have not planned to add a special support for the obsolete syntax to output warning. It would bring just bloated maintenance cost.

**Comment by spkane** [comment]
I do want to point out that some people, like myself, likely only use this tool every few months, so a month is probably not really long enough to announce a deprecation, but since the application is still in active development and catching these sorts of errors may not be easy to implement and maintain I understand your decision to close this.
