### ISSUE TITLE
Are there any way to make a two-columns PDF file by marp-cli

### ISSUE THREAD

**Issue by ptlddn** [marp-team/marp-cli#194]
Marp is a nice software for presentation
Now I wondering if there is any way to add a column  feature to Marp？

**Comment by yhatt** [comment]
Duplicated question with https://github.com/marp-team/marp-core/issues/132. Please refer to it.

**Comment by yhatt** [comment]
FYI: You may use raw HTML in Marp Markdown with a way as same as [reveal.js](https://github.com/hakimel/reveal.js/) presentation (Marp CLI has to enable `--html` option).
https://stackoverflow.com/questions/30861845/how-to-use-two-column-layout-with-reveal-js
