### ISSUE TITLE
"r.emulateMediaType is not a function" error when exporting images

### ISSUE THREAD

**Issue by igrr** [marp-team/marp-cli#195]
I am running into an error when converting markdown into images using `--image` or `--images` flag. This can be reproduced with the following `test.md` file:

```markdown
# Title

content
```

I am running marp-cli using the official Docker image:
```bash
$ docker run --rm -v $PWD:/build -w /build marpteam/marp-cli --image png test.md
[  INFO ] Converting 1 markdown...
[ ERROR ] Failed converting Markdown. (r.emulateMediaType is not a function)
```

Version:
```bash
$ docker run --rm marpteam/marp-cli --version
@marp-team/marp-cli v0.16.2 (w/ @marp-team/marp-core v0.15.2)
```

At the same time, conversion to PDF works fine.

The issue was not present in marpteam/marp-cli:v0.15.1 Docker image.

**Comment by yhatt** [comment]
Thanks for your report. :smiley:

I guess it causes by different Puppeteer version in docker image. We are using compatible version with Chromium that was installed to alpine image, and typically it becomes a bit older than for master branch.

`emulate MediaType` is a new API provided by Puppeteer v2, so the conversion within our container image would fail if it had used v1. Probably we have to give a fallback into v1's deprecated function `emulateMedia`.

**Comment by yhatt** [comment]
Now the `latest` image has installed compatible Chromium 79 with Puppeteer v2.

```
$ docker pull marpteam/marp-cli
$ docker run --rm --init -v $PWD:/home/marp/app/ -e LANG=$LANG marpteam/marp-cli markdown.md --image png
[  INFO ] Converting 1 markdown...
[  INFO ] markdown.md => markdown.png
```
