### ISSUE TITLE
marp-cli can not export pdf on window

### ISSUE THREAD

**Issue by xulongzhe** [marp-team/marp-cli#216]
like your project so much, but on my enviroment it can not export pdf only, but html and pptx is ok!

here is my test source file:

```md
---
marp: true
---

# Test
```

and here is my command:

```
C:\Users\x02454>marp --pdf C:\Users\x02454\Desktop\test.md
[  INFO ] Converting 1 markdown...
[ ERROR ] Failed converting Markdown. (Protocol error (IO.read): Invalid parameters handle: string value expected)

C:\Users\x02454>marp --html C:\Users\x02454\Desktop\test.md
[  INFO ] Converting 1 markdown...
[  INFO ] Desktop\test.md => Desktop\test.html

C:\Users\x02454>marp --pptx C:\Users\x02454\Desktop\test.md
[  INFO ] Converting 1 markdown...
[  INFO ] Desktop\test.md => Desktop\test.pptx
```

> my os version:  win10 ltsb 1607

thank you very much, and hope it better!

**Comment by yhatt** [comment]
Probably the reported error has related to puppeteer/puppeteer#4609. Would you try to update Marp CLI and Google Chrome to the latest stable version?

**Comment by xulongzhe** [comment]
it's work, thanks a lot.
