### ISSUE TITLE
It dosen't work for me.

### ISSUE THREAD

**Issue by slatbox** [marp-team/marp-cli#219]
How to fix this:

[  INFO ] Converting 1 markdown...
[ ERROR ] Failed converting Markdown. (Could not find browser revision 737027. Run "npm install" or "yarn install" to
          download a browser binary.)

**Comment by yhatt** [comment]
Probably [Google Chrome] is not installed in your environment. You can see [this notice in README.md](https://github.com/marp-team/marp-cli#try-it-now):

> :information_source: You have to install [Google Chrome] (or [Chromium]) to convert slide deck into PDF, PPTX, and image(s).

[google chrome]: https://www.google.com/chrome/
[chromium]: https://www.chromium.org/

**Comment by slatbox** [comment]
Oh I see.Yes it is because of chrome.Thanks a  lot. @yhatt

**Comment by yhatt** [comment]
:+1:

I think there is room for improvement in this error message because of misleading.

**Comment by yhatt** [comment]
Created new issue #220 about the problem of error message. Close to mark this as resolved.

**Comment by carlee0** [comment]
@yhatt I received the some error message. And I am absolutely certain that I have Chromium installed.

**Comment by yhatt** [comment]
Typically Marp should show "`Failure to export. It requires to install Google Chrome (or Chromium) for exporting.`" if lacked Chrome. In this case, try to set custom chrome path in extension setting, and export again after restart VS Code.

If you met to "`Could not find browser revision`...", that is unexpected error. Something wrong might have been occurred while installation of extension. Try re-install Marp extension.

**Comment by carlee0** [comment]
Thank you for your reply. I've added the chrome path in the extension setting and restarted VSCodium (could this be the problem?). The error message changed: "`Failure to export: [CLIError] Failed converting Markdown. (Protocol error (Target.setDiscoverTargets): Target closed.`)". It seems to be unrelated to marp this time...

**Comment by yhatt** [comment]
This is another probability if you are using Linux:

> **NOTE:** We've known to fail the export command if both of VS Code and Chromium have installed by snap: [marp-team/marp-cli#287](https://github.com/marp-team/marp-cli/issues/287). It's probably insecure but setting custom Chrome path to [the raw binary of snap Chromium](https://github.com/marp-team/marp-cli/issues/287#issuecomment-693500881) may help you as a workaround.
>
> _&dash; https://github.com/marp-team/marp-vscode/releases/edit/v0.15.1_

**Comment by carlee0** [comment]
@yhatt Sorry, I don't think that is the issue. I am on Mac and I installed VSCodium with brew, Chromium from binary.

**Comment by yhatt** [comment]
OK, I can reproduce the same error in macOS when setting `/Applications/xxxxxx.app` as Chrome path.

It's actually a wrong path so you have to set like `/Applications/xxxxxx.app/Contents/MacOS/xxxxxx`. See also: https://github.com/marp-team/marp-vscode/issues/84#issuecomment-543485302

**Comment by carlee0** [comment]
Setting the path to `/Applications/Chromium.app/Contents/MacOS/Chromium` and restart VSCodium did the trick! :) Thank you so much, @yhatt!

**Comment by 5mechang** [comment]
@yhatt I got a similar error `Failure to export: [CLIError] Failed converting Markdown. (Protocol error (Target.setAutoAttach): Target closed.)` with different settings.
My OS is Windows 11 and the path to Microsoft Edge is set, while I'm not sure how I can set the path to chromium within Edge.

**Comment by yhatt** [comment]
@5mechang Normally Marp in Windows will automatically find out a proper executable of MS Edge without specifying the browser path manually. Try with no specific path settings.

> Please help us to post to [GitHub Discussions](https://github.com/marp-team/discussions) rather than taking over closed issues.

**Comment by 5mechang** [comment]
@yhatt Thank you for your quick response. Unfortunatelly the error hasn't been solved with no path. I'll check the settings of the PC which can export successfully.
