### ISSUE TITLE
[ERROR] The specified engine has not resolved.

### ISSUE THREAD

**Issue by simonmaris** [marp-team/marp-cli#224]
Hi! 

For some reason, I seem to be unable to define an engine for marp-cli. I was going to add custom markdown-it plugins, but have tested this minimal example to show the problem. 

![Screen Shot 2020-05-01 at 16 31 46](https://user-images.githubusercontent.com/861414/80812971-5ccf5380-8bc9-11ea-857d-746d396400fe.png)

The same error message happens when I tried to add `--engine ./engine.js` with the following:

```
const { Marp } = require('@marp-team/marp-core')
const markdownItFootnote = require('markdown-it-footnote')

module.exports = (opts) => new Marp(opts).use(markdownItFootnote)
```

Any ideas? 

Thank you very much for building this!

**Comment by yhatt** [comment]
You're lacking a step to install modules. As shown in [the example](https://github.com/marp-team/marp-cli#example-markdown-it-mark), the custom engine has to install Marp Core package and plugins through npm package manager individually.

```
npm i @marp-team/marp-core markdown-it-footnote --save-dev
```

**Comment by simonmaris** [comment]
I installed both before globally. Do they need to be local?

**Comment by yhatt** [comment]
Yep. [Global install is generally evil](https://stackoverflow.com/questions/39833614/is-installing-things-globally-from-npm-a-bad-practice).

**Comment by simonmaris** [comment]
Right, that's unfortunate. 
I was hoping to use marp-cli on multiple presentations without scattering node-modules/ directories everywhere. This (also discussed on SO) is from the npm release logs v1.0 (year 2011 :))

> In general, the rule of thumb is:
> 1. If you’re installing something that you want to use in your program, using require('whatever'), then install it locally, at the root of your project.
> 2. If you’re installing something that you want to use in your shell, on the command line or something, install it globally, so that its binaries end up in your PATH environment variable.

Obviously not up-to-date but I couldn't find anything in the latest docs.. I was hoping to do 2., would there be a way to still do this (knowingly running into version issues later)?

Thank you!

**Comment by yhatt** [comment]
@simonmaris I found out a way to enable global modules.

```bash
NODE_PATH=$(npm root -g) marp --engine @marp-team/marp-core
```

Node.js's `require()` does not find from global modules by default. By adding `NODE_PATH` env, you can add the target directory for finding.

**Comment by simonmaris** [comment]
WOW, thank you, that's fantastic! 

May I ask one last question? 😇 
I would like to [customize the markdown-it-footnote output](https://www.npmjs.com/package/markdown-it-footnote#customize), however I am struggling to add this the right way.

```
const md = require('markdown-it')().use(require('markdown-it-footnote'));
 
md.renderer.rules.footnote_block_open = () => (
  '<h4 class="mt-3">Footnotes</h4>\n' +
  '<section class="footnotes">\n' +
  '<ol class="footnotes-list">\n'
);
```

I couldn't find any examples of a custom engine that extends md.renderer.rules. I saw the official plugins [like math](https://github.com/marp-team/marp-core/blob/master/src/math/math.ts) using marpitPlugin, would this be the way to go?

I would be very grateful for a pointer or basic example!

**Comment by yhatt** [comment]
https://github.com/marp-team/.github/blob/master/CONTRIBUTING.md#report-issue

> Please not contain multiple reports into one issue. It should have only one theme.
