### ISSUE TITLE
Blurry text in server mode

### ISSUE THREAD

**Issue by drewdavis21** [marp-team/marp-cli#225]
When I am running in server mode or even just running `marp` to output an HTML file, text is really blurry (see below).
![image](https://user-images.githubusercontent.com/9686215/80834761-520fc100-8bbf-11ea-98a7-f976815d8a67.png)

When setting the output to PDF, it renders fine. I ran it with the built-in themes as well, and the same issue occurs. Any ideas?

**Comment by yhatt** [comment]
Which browser is opening previewed server / HTML?

If you are using Safari, would not get better rendering because of [using polyfill to avoid long standing Webkit bug](https://github.com/marp-team/marpit-svg-polyfill#why-need). Try using non WebKit browser.

**Comment by drewdavis21** [comment]
Ahh, I was using Safari. I'll use Firefox instead. Thanks!
