### ISSUE TITLE
defining md.renderer.rules in custom engine with markdown-it-plugins

### ISSUE THREAD

**Issue by simonmaris** [marp-team/marp-cli#226]
I am trying to create a custom engine combining marp-core and markdown-it-footnote to use with marp-cli. Currently my engine.js file looks like this: 

```
const { Marp } = require('@marp-team/marp-core')
const markdownItFootnote = require('markdown-it-footnote')

const md = require('markdown-it')().use(require('markdown-it-footnote'));
```
This works great, but I would like to [customize the markdown-it-footnote output](https://www.npmjs.com/package/markdown-it-footnote#customize), however I am struggling to add this the right way.

```
const md = require('markdown-it')().use(require('markdown-it-footnote'));
 
md.renderer.rules.footnote_block_open = () => (
  '<h4 class="mt-3">Footnotes</h4>\n' +
  '<section class="footnotes">\n' +
  '<ol class="footnotes-list">\n'
);
```

I couldn't find any examples of a custom engine that extends md.renderer.rules. I saw the official plugins like [math](https://github.com/marp-team/marp-core/blob/master/src/math/math.ts) using marpitPlugin, would this be the way to go?

I would be very grateful for a pointer or basic example!

**Comment by yhatt** [comment]
Thanks for helping to manage issues (https://github.com/marp-team/marp-cli/issues/224#issuecomment-622926920). Try this if using Marp CLI's custom engine:

```javascript
// custom-engine.js
const { Marp } = require('@marp-team/marp-core')
const markdownItFootnote = require('markdown-it-footnote')

module.exports = (opts) => {
  const md = new Marp(opts).use(markdownItFootnote)

  // Customize renderer
  md.renderer.rules.footnote_block_open = () => (
    '<h4 class="mt-3">Footnotes</h4>\n' +
    '<section class="footnotes">\n' +
    '<ol class="footnotes-list">\n'
  );

  return md
}
```

**NOTE**: [markdown-it-footnote](https://github.com/markdown-it/markdown-it-footnote) is known as one of plugin not compatible with Marp / [Marpit](https://marpit.marp.app/usage?id=extend-marpit-by-plugins). Probably it would not work as you expected.

**Comment by simonmaris** [comment]
Thank you, I changed `md.renderer.rules.footnote_block_open = …` to `md.markdown.renderer.rules.footnote_block_open = …` and it worked. 
But yes, I obviously should have thought about the issue of footnote insertion in general more before going down this road.. I see it was disussed earlier [here](https://github.com/yhatt/marp/issues/2).

Is this still on the roadmap to get something like footnotes on a slide/section basis?

Another idea I had was to add a directive, sort of like footer and header, that way it would at least be easy to have a box somewhere on the slide to but image credits / links etc into. In a presentation that would be all I would use footnotes for. The styling and positioning would be much easier this way.

**Comment by yhatt** [comment]
Marpit and Marp Core must follow [CommonMark](https://commonmark.org/), and _footnote is not part of CommonMark_ so we have not any plan for built-in support. Marp team has a policy that we should not break CommonMark as far as possible.

We have well-documented [Marpit API](https://marpit-api.marp.app/) to help making third-party plugins by our community. I wish that community develops and provides Marpit plugin for footnote per each slides.

FYI Marp community has a precedent using [`markdown-it-container`](https://github.com/markdown-it/markdown-it-container) as a footnote block: [guoxue-study/tongjian](https://github.com/guoxue-study/tongjian#%E6%B7%BB%E5%8A%A0%E8%84%9A%E6%B3%A8) (Chinese). The definition of `engine.js` is [here](https://github.com/guoxue-study/tongjian/blob/master/tools/cli/engine.js).

**Comment by yhatt** [comment]
About markdown-it-footnote is off-topic in this issue. Close to mark as resolved the original question.

**Comment by simonmaris** [comment]
The link to tongijan looks like a good workaround, I will explore it further! 

Thank you so much for your help today and yesterday! 
I was going to close, you beat me by seconds :)

**Comment by StefanZander** [comment]
Hi @simonmaris, I have a rather similar workflow and also would like to use footnotes in my markdonw-based slides.
So my question is: how did you manage to get the footnote-plugin to work with marp-cli and are footnotes placed on only on the slides on which they were defined?

Can you, maybe, post your solution?

When I added footnotes to one slide, they are rendered adjacent to the header and footer section on every slide and listed only on the last slide.

Thanks in advance!

**Comment by jtppragg** [comment]
Hi @StefanZander, maybe this solution works also for you: https://github.com/marp-team/marp-cli/issues/300#issuecomment-727890849

**Comment by spkane** [comment]
This was mentioned in the [comments above](https://github.com/marp-team/marp-cli/issues/226#issuecomment-622943585), but for easier discovery, there is a typo in this code block.

`md.renderer.rules.footnote_block_open` should read `md.markdown.renderer.rules.footnote_block_open`

> ```js
> // custom-engine.js
> const { Marp } = require('@marp-team/marp-core')
> const markdownItFootnote = require('markdown-it-footnote')
> 
> module.exports = (opts) => {
>   const md = new Marp(opts).use(markdownItFootnote)
> 
>   // Customize renderer
>   md.renderer.rules.footnote_block_open = () => (
>     '<h4 class="mt-3">Footnotes</h4>\n' +
>     '<section class="footnotes">\n' +
>     '<ol class="footnotes-list">\n'
>   );
> 
>   return md
> }
> ```
>
