### ISSUE TITLE
Server Mode will not start if absolute path to presentation contains opening parentheses `(`

### ISSUE THREAD

**Issue by dennisppaul** [marp-team/marp-cli#227]
trying to run marp-cli in server mode fails if the directory ( or any directory in the absolut path to the directory ) contains an opening parenthesis `(`. for example:

`marp -s -I hello\(world`

will bring up the *Usage Page* instead of starting *Server Mode*. this behavior occurs on MacOS 10.15 in bash shell.

**Comment by yhatt** [comment]
It's similar to #95. I think it has recognized wrongly as glob pattern. It was fixed path resolution for the file in #117 but probably didn't fixed for the directory.

**Comment by yhatt** [comment]
Resolved in the latest release [v0.18.0](https://github.com/marp-team/marp-cli/releases/tag/v0.18.0). Please re-open issue if still failed.
