### ISSUE TITLE
Can you release applications for windows 32-bit platform?

### ISSUE THREAD

**Issue by linpengcheng** [marp-team/marp-cli#228]
Can you release applications for windows 32-bit platform?

**Comment by yhatt** [comment]
We don't yet provide The *EXPERIMENTAL* standalone binary for Windows 32-bit (x86). The legacy arch such as 32-bit is towarding to deprecate slowly so Marp team does not feel like working for that. [It is backed up by the fact that 32-bit Windows 10 for OEM is no longer provided in the latest update.](https://docs.microsoft.com/en-us/windows-hardware/design/minimum/minimum-hardware-requirements-overview#section-30---minimum-hardware-requirements-for-windows10-for-desktop-editions)

>  Beginning with Windows 10, version 2004, all new Windows 10 systems will be required to use 64-bit builds and Microsoft will no longer release 32-bit builds for OEM distribution.

But [the packaging tool `pkg`](https://github.com/vercel/pkg) we are using can build the binary for x86 arch so we anytime welcome for contribution to update our packaging script.

**Comment by yhatt** [comment]
...and don't forget you can still use [Marp CLI through Node.js](https://github.com/marp-team/marp-cli#npx) even if you are using x86 arch.

**Comment by yhatt** [comment]
Closed for housekeeping. 🧹
