### ISSUE TITLE
Docker: Could not find or parse configuration file

### ISSUE THREAD

**Issue by varac** [marp-team/marp-cli#244]
I'm following the instructions from https://hub.docker.com/r/marpteam/marp-cli but marp fails:

```
❯ docker run --rm -v $PWD:/home/marp/app/ -e LANG=$LANG marpteam/marp-cli slide.md
[ ERROR ] Could not find or parse configuration file.
```

I don't have a config file since marp installed from npm works fine without it.

```
❯ marp slide.md 
[  INFO ] Converting 1 markdown...
[  INFO ] slide.md => slide.html
```

**Comment by yhatt** [comment]
I tried but could not reproduce. By guessing from the message, it's probably throwing the error while searching the config file.

Please review the permission for these files if you have the configurable file in the same directory: `marp.config.{js,json,yml,yaml}`, `.marprc.{js,json,yml,yaml}`, and `package.json` (Marp CLI will try to parse `marp` section in `package.json`).

An installed `marp` command might be able to access into configs with high authority if you had installed with wrong `sudo`.

**Comment by varac** [comment]
It was insufficient file/directory permissions on the mounted volume, so my bad. Sorry for the noise !

**Comment by rogerperkin** [comment]
@varac what was your fix as I am having the same issue
