### ISSUE TITLE
Custom font when export pdf

### ISSUE THREAD

**Issue by markho** [marp-team/marp-cli#245]
Custom font when export to PDF

When output md file to Chinese character environment, I found it always output as PMingLiu, is it possible to change like following .css template modified from the introduction?
`
@import "gaia";

section {
  background: #FFF;
  
}
section.header {
  color: white;
  font-family: "Microsoft YaHei";
  font-size: 60px;
  text-align: center;
}
`

**Comment by yhatt** [comment]
The similar question #161 may help you. CSS definitions in `section.header` class would not be used unless specify class as `header` explicitly, so it's important to place `font-family` in global `section` selector instead of `section.header`.

**Comment by markho** [comment]
Many thanks, yes, it is a duplicated one, thanks for your great work.
