### ISSUE TITLE
Animated GIF Loads for HTML Output - Not PPTX

### ISSUE THREAD

**Issue by engineerjoe440** [marp-team/marp-cli#249]
I was playing around, trying to add an animated GIF to my markdown so that it could be embedded to help illustrate concepts for my generated slide-deck. Loading the GIF from a web resource, I was able to perform the load appropriately for the HTML slide-deck, but if I were to try to generate a PowerPoint presentation, the image did not load.

![image](https://user-images.githubusercontent.com/33275230/87697464-f75e1e00-c746-11ea-94b4-9f51c639ac3a.png)

For fun, I tried loading the GIF as a local file and using the `--allow-local-files` flag in the command, and although I was able to load a *static* shot of the image, the animation did not load correctly. Am I missing something, or do you have any thoughts on how embedding an animated GIF in a PPTX might be possible?

I understand that this may be a bit challenging to load into the PPTX, but if there's any possible way, I think this has **great value**! What do you think?

**Comment by yhatt** [comment]
PPTX conversion is the feature in Marp CLI, not in Marpit framework. Translated issue from Marpit :arrow_forward: Marp CLI.

...and it's duplicated with #196. Refer to #196 and https://github.com/marp-team/marp-cli/issues/166#issuecomment-536827067 for why cannot play GIF in PPTX.

**Comment by engineerjoe440** [comment]
Ah!!! My mistake.... Thank you for pointing me there!
