### ISSUE TITLE
errors in npm outdated -g after installing marp-cli@0.20.0

### ISSUE THREAD

**Issue by CyrusYip** [marp-team/marp-cli#270]
There were errors in output of `errors in npm outdated -g` after installing marp-cli@0.20.0 by `npm install -g @marp-team/marp-cli`.

I use npm mirror. Did it caused the errors. How can I fix them??

```shell
~ npm outdated -g
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @marp-team/marp-cli@^0.20.0.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/hunter/.npm/_logs/2020-08-14T14_02_11_626Z-debug.log
```

[2020-08-14T13_31_13_939Z-debug.log](https://github.com/marp-team/marp-cli/files/5075021/2020-08-14T13_31_13_939Z-debug.log)

**Comment by yhatt** [comment]
Your mirror seems not to provide the latest Marp CLI v0.20.0. https://registry.npm.taobao.org/@marp-team%2fmarp-cli shows mirroring only versions up to v0.19.0.

![Screenshot_2020-08-15 https registry npm taobao org](https://user-images.githubusercontent.com/3993388/90278928-32b54f00-dea3-11ea-8dde-a476abfc6996.png)

Try updating with official npm repository or another mirrors if possible.
