### ISSUE TITLE
Add watermark feature

### ISSUE THREAD

**Issue by blurayne** [marp-team/marp-cli#272]
Hi,

I would need a watermark feature, meaning a logo that always stays fixed on top of all slides. When a slide transitions this would also stay on top. Which is the best way to implement this? Style probably needs to change on some slides (like inverted logo for inverse slides).

Similar to that would be a copyright notice that would have the same behavior. Style probably needs to change on some slides.

__
I just started a presentation and new theme on this awesome project (and i like it much more than GitPitch).I do hope MARP now becomes standard for presentations on GitHub.

**Comment by yhatt** [comment]
Thanks for using Marp!

Marp relies on the power of CSS, and I've designed Marp that the `::before` pseudo-element of the root `section` is working as some overlay contents, like the watermark. The example for the constant watermark is here:

```markdown
---
marp: true
---

<style>
section::before {
  position: absolute;
  display: flex;

  /* Copyright text */
  content: "(C) 2020 xxxxxxxxxx";
  font-size: 20px;
  color: #000;
  padding-left: 220px;
  align-items: center;

  /* Position and size */
  left: 30px;
  bottom: 30px;
  height: 64px;

  /* Watermark image */
  background: url("https://raw.githubusercontent.com/marp-team/marp/master/marp.png") no-repeat left center;
  background-size: contain;
  opacity: 0.3;

  /* Allow to control elements under the watermark */
  pointer-events: none;
}

section.invert::before {
  /* You can set other styles in invert color scheme */
  filter: invert(1);
}
</style>

# The example of watermark

---

<!-- _class: invert -->

# The example of watermark

Watermark is working also with splitted background.

![bg left](https://images.unsplash.com/photo-1476764329498-e89f194558e1?crop=entropy&cs=tinysrgb&fit=crop&fm=jpg&h=720&ixid=eyJhcHBfaWQiOjF9&ixlib=rb-1.2.1&q=80&w=1280)
```

![1](https://user-images.githubusercontent.com/3993388/90614015-11f34d80-e245-11ea-99ed-d2a7ee629747.jpg)
![2](https://user-images.githubusercontent.com/3993388/90614024-1455a780-e245-11ea-93aa-a1230ae8a5e1.jpg)
