### ISSUE TITLE
Generate presenter notes

### ISSUE THREAD

**Issue by Serhioromano** [marp-team/marp-cli#278]
In every slide you can add notes in `<!--  -->` which will not be a part of a slide but those are presenter notes.

Would be nice to add parameter like `--notes` that will alongside generating slides, will also generate separate TXT file with only notes in there. this way you can generate a slide and presenter notes file later to be used on teleprompter or print for hints during presentation.

**Comment by Serhioromano** [comment]
@yhatt cannot believe it! Thank you.

**Comment by yhatt** [comment]
We have to make a grateful for @chrisns's work!
