### ISSUE TITLE
Columns, aka HTML

### ISSUE THREAD

**Issue by ricardo-reis-1970** [marp-team/marp-cli#282]
I'm aware that Markdown is not HTML, but all flavours of it seem to allow for HTML (and/or LaTeX) natively. With Marp I can do neither.

I'm trying to have columns layout, just like PowerPoint has. For now, my strategy is limited to adding `<style scoped></style>` sections to the intended slides. My options are:
```
section {
  column-count: 2;
}
```
in which case, the entire slide becomes 2 columns, including the title, or:
```
p {
  column-count: 2;
}
```
in which case each paragraph is split across columns, as dictated by its length.

If I attempt to inject any HTML into the slide content, it will be rendered as text. The idea was to wrap the columns in a `<div class='2cols'>` and define `2cols` as a global style. The documentation says:
* For security reason, HTML tag only allows *whitelisted* elements by default.

I could not find any definition of whitelisted elements, not even in the [CommonMark Spec](https://spec.commonmark.org/0.29/#html-blocks).

A half way decent alternative is the following style:
```
<style scoped>

section {
  column-count: 2;
}
h1 {
  column-span: all;
}
p {
  margin: 0;
}
</style>
```
that breaks the title out of columns, but it is a bit convoluted and it requires removing the top margin from `p` in order to avoid differences from 1st to 2nd column.

Is there any possibility to inject a `<div>`?

**Comment by yhatt** [comment]
Duplicated with #194. Simply add `--html` option if you want to use HTML tags like `<div>`.

See also: https://github.com/marp-team/marp-core/issues/132#issuecomment-555101747

**Comment by ricardo-reis-1970** [comment]
Dear Yuki,

You are *FAST* to reply. Thank you! I've been all over the place because I just started and I have almost 3 decades of Microsoft bad habits to leave behind. Thank you!

It's just that many of these things are not too obvious in the docs, neither is this the ideal place to exchange letters. Just give me time to learn this well and I promise you documentation revisions and possibly a course on Marp... with presentations built in Marp, obviously!

Thank you for your patience!
Ricardo
