### ISSUE TITLE
When making pdf output, bg image becomes invisible

### ISSUE THREAD

**Issue by nkjmsss** [marp-team/marp-cli#293]
If image is loaded like below (as bg image), bg image becomes invisible. It only happens in pdf output.

```markdown
![bg contain](img/sample.png)
```

I'm using Mac OS 10.15.6 and Node v12.16.2.

**Comment by yhatt** [comment]
Didn't you see a warning message about local resources when generating PDF?

```
[  WARN ] Marp CLI has detected accessing to local file. That is blocked by security reason. Instead we recommend using assets uploaded to
          online. (Or you can use --allow-local-files option if you are understood of security risk)
```

Try using `--allow-local-files` option as written in warning.

**Comment by yhatt** [comment]
[A reproducible example](https://github.com/AseiSugiyama/marp_test) was provided in the issue tracker of Marp for VS Code (marp-team/marp-vscode#175), and I've confirmed not rendered background images in Marp CLI too.

Identify this issue as a bug, and going to find out a workaround to avoid a problem by upstream Chrome.

**Comment by yhatt** [comment]
We will patch for workaround in the next release: #294. If you are still using the current release, you also can try using `--template bare` option.
