### ISSUE TITLE
Build linux/arm64 container images in addition to the linux/amd64 ones

### ISSUE THREAD

**Issue by spkane** [marp-team/marp-cli#328]
This will help support folks on things like Raspberry Pis and Apple Silicon Macs.

**Comment by spkane** [comment]
Images could be tagged something like `amd64-v0.23.2` and `arm64-v0.23.2`

**Comment by spkane** [comment]
Note, that I have tried building the `Dockerfile` on my Apple Silicon Mac and so far that seems to work just fine without any changes. Docker pulls the node base image for the correct arch, and so far, so good.

**Comment by yhatt** [comment]
Now we've set up automated build for multi-arch images including ARM64 by working in #339. 

But currently it makes over 3x slower to build because using ARM emulation on x64 environment in CircleCI.

**Comment by spkane** [comment]
Thank you @yhatt! I just switched off my custom build image and tested this out today and it appears to be working great.
