### ISSUE TITLE
Marp don't use chromium installed via flatpak

### ISSUE THREAD

**Issue by vroger11** [marp-team/marp-cli#333]
Exporting pdf is not working even if Chromium is installed via flatpak.

OS: Ubuntu 20.04

Note: it works if the snap version is installed, but it is not convenient to keep two chromium browers on my system (as the flatpak one start faster and is globally more responsive).

**Comment by yhatt** [comment]
Marp CLI is depending on [chrome-launcher](https://github.com/GoogleChrome/chrome-launcher) by Chrome team, to resolve installed Chrome, and it has not supported finding flatpak binary. You have to specify the path manually through `CHROME_PATH` env.

```
CHROME_PATH=/var/lib/flatpak/exports/bin/org.chromium.Chromium marp your-markdown.md --pdf
```

**Comment by vroger11** [comment]
Ok thank you a lot it works. Maybe this info can be useful in the readme? (under the pdf exporting information)

**Comment by ruben-rodriguez** [comment]
Very useful for me too, as I have installed a chromium based browser. 
Thank you @yhatt !
