### ISSUE TITLE
Customising top and bottom black bars

### ISSUE THREAD

**Issue by danielepolencic** [marp-team/marp-cli#358]
I tried to search for a solution in this repository and in the marp-team/core. I could not make it work, hence the question.
I want to customise the `<body>` of the presentation so that the slides are presented on a white background.

I added the following directive to my markdown:

```md
---
style: |
  body {
    background: red !important
  }
---

... slides here
```

However, I cannot remove the black bars.
![image](https://user-images.githubusercontent.com/1130499/122157790-0c36ba80-ce9e-11eb-9737-dfa93d787659.png)

What should I try next?

Thanks.

**Comment by yhatt** [comment]
`<body>` is out of scope for tweaking style by Markdown and the style of Marp CLI template cannot customize. You should create HTML manually by using `@marp-team/marp-core`.

- Example of the base framework Marpit: https://marpit.marp.app/?id=how-to-use
- Related: marp-team/marp#89

<details>
<summary>Actually it's not impossible but we do NEVER recommend</summary>

```markdown
---
style: |
  @import url('data:text/css,body{background:white;}');
---
```

The external stylesheet imported by `@import url('...')` will not scope to slides. It is always at the global.

But customizing style of the outside of slide will lose the portability of Marp Markdown for other ecosystem integrations (e.g. Marp for VS Code, Marp Web, 3rd party tools, web-embeded slide, etc). We do NEVER recommend.
</details>

**Comment by danielepolencic** [comment]
Understood, thanks for the prompt response.

**Comment by yhatt** [comment]
**UPDATE:** The latest [Marp CLI v1.5.0](https://github.com/marp-team/marp-cli/releases/tag/v1.5.0) follows [the update of the base framework Marpit](https://github.com/marp-team/marpit/releases/tag/v2.2.0). It can style the slide container through [`::backdrop` CSS selector](https://developer.mozilla.org/docs/Web/CSS/::backdrop).

Now you can change the black backdrop without hack:

```markdown
---
style: |
  ::backdrop {
    background: red;
  }
---
```
