### ISSUE TITLE
node.js < 12 not supported

### ISSUE THREAD

**Issue by jlevon** [marp-team/marp-cli#359]
### Version of Marp Tool

latest

### Operating System

Linux

### Environment

ubuntu version:

$ cat /etc/debian_version 
bullseye/sid

$ npx --version
6.14.4

### How to reproduce

```
$ make
npx @marp-team/marp-cli --pdf --allow-local-files -o ioregionfd.pdf ioregionfd.md
npx: installed 265 in 26.365s
yargs supports a minimum Node.js version of 12. Read our version support policy: https://github.com/yargs/yargs#supported-nodejs-versions
make: *** [Makefile:3: ioregionfd.pdf] Error 1
```

### Expected behavior

This was still working until recently

### Actual behavior

Can run via npx as described in the README

**Comment by yhatt** [comment]
The latest Marp CLI ([v1.0.0+](https://github.com/marp-team/marp-cli/releases/tag/v1.0.0)) has already dropped the support for Node.js < 12 in accordance with [Node.js maintenance schedule](https://nodejs.org/en/about/releases/).

https://github.com/marp-team/marp-cli/blob/91ad8c05b34c57fb5c1d68bb57c497ad17b6cf59/package.json#L28-L30

Probably you're using Node.js < 12 and _it has already reached End-Of-Life_. Please upgrade your Node.js to the supported version (>= 12).

When the updation is blocking by a special reason, you can use [the latest release of Marp CLI v0.x.x](https://github.com/marp-team/marp-cli/releases/tag/v0.23.3) as a workaround.

```bash
npx @marp-team/marp-cli@^0.23.3
```

**Comment by jlevon** [comment]
Ubuntu is a pretty popular operating system, maybe it's worth documenting this in the install instructions rather than just closing the issue?

**Comment by yhatt** [comment]
@jlevon We're always welcome for your pull request to add Node.js requirement.

**Comment by yhatt** [comment]
-> #361
