### ISSUE TITLE
The inline CSS in Markdown is not work.

### ISSUE THREAD

**Issue by aquastripe** [marp-team/marp-cli#364]
### Version of Marp Tool

Marp CLI v1.1.1

### Operating System

Linux

### Environment

- OS version: Ubuntu 20.04.2
- Node.js version (Marpit / Marp Core/ Marp CLI): [e.g. Node.js 14.17.1]
    - Node.js: v14.15.3
    - Marp CLI: v1.1.1
- VS Code version (Marp for VS Code): [e.g. VS Code 1.57.1]
    - VS Code: 1.58.2

### How to reproduce

1. type a command like this:
    ```bash
    marp some.md -o some.html
    ```

### Expected behavior

![expected](https://user-images.githubusercontent.com/73936909/126400263-4dec4f90-5acb-44ec-9ec2-0b7982e598f4.png)

It's ok in VS Code extension like this.

### Actual behavior

![actual](https://user-images.githubusercontent.com/73936909/126400216-5c9534d9-d17f-49e6-931a-a823ca408745.png)

The source file is the same, but the inline CSS is failed to render in marp-cli.
It's ok with an additional `--html` flag in marp-cli.

**Comment by yhatt** [comment]
> It's ok with an additional `--html` flag in marp-cli.

Yes, every Marp tools require opt-in to enable HTML, to save you from any suspicious activity. Please enable HTML via `--html` option whenever using HTML tags.

Close because it is not a bug.

**Comment by aquastripe** [comment]
> > It's ok with an additional `--html` flag in marp-cli.
> 
> Yes, every Marp tools require opt-in to enable HTML, to save you from any suspicious activity. Please enable HTML via `--html` option whenever using HTML tags.
> 
> Close because it is not a bug.

Thanks for your reply.

I found that I checked "Enable HTML" in VS Code Extension corresponding to the '--html' option in CLI.
I forgot it and misreported it as a bug. Sorry about that.
