### ISSUE TITLE
Metadata in PDF export

### ISSUE THREAD

**Issue by dwschmid** [marp-team/marp-cli#367]
Metatdata such as
```
title: A title
description: A nice presentation
```
does not seem to make it as metadata / properties into exported PDF files. Would be useful to have the standard ones, i.e. title, author, subject, keywords.

**Comment by yhatt** [comment]
Transfered from Marp for VS Code ➡️ Marp CLI 🚚. PDF export is the role of CLI. (Diagram: https://github.com/marp-team/marp/discussions/126#discussioncomment-1021103).

Related:

- https://github.com/puppeteer/puppeteer/issues/3054 (Rejected)
