### ISSUE TITLE
Converting to PDF does not work if CHROME_PATH is not set

### ISSUE THREAD

**Issue by lk16** [marp-team/marp-cli#387]
### Version of Marp Tool

Marp CLI v1.4.0

### Operating System

Linux

### Environment

- OS version: Linux Mint 20.1
- Node.js version: not sure, I'm using the linux binary from your releases page with version 1.4.0. Also, `which node` and `which nodejs` both return nothing.
- VS Code version: irrelevant, it's a CLI-related problem

### How to reproduce

Without `CHROME_PATH` environment variable set:

```
$ marp --pdf file.md                                                                                                         
[  INFO ] Converting 1 markdown...                                                                                                                             
[  WARN ] The CHROME_PATH environment variable must be set to a Chrome/Chromium executable no older than Chrome stable.
[ ERROR ] Failed converting Markdown. (You have to install Google Chrome, Chromium, or Microsoft Edge to convert slide deck with current options.)
$ ls file.pdf                                 
ls: cannot access 'file.pdf': No such file or directory
```

With that variable set:
```                                                                        
$ CHROME_PATH=`which brave-browser` marp --pdf file.md 
[  INFO ] Converting 1 markdown...
[  INFO ] file.md => file.pdf  
$ ls file.pdf
file.pdf
```

### Expected behavior

The PDF file is generated without `CHROME_PATH` set.

### Actual behavior

It fails to generate the PDF file.

### Additional information

While typing this out, I'm starting to suspect that the specified binary is actually used for conversion.
If that's the case, please excuse me for wasting your time.

I would be confused though, why is this CLI tool depending on a browser to be installed to convert a text file to a PDF?

**Comment by yhatt** [comment]
You're right. Marp CLI really converts Markdown into several formats (PDF, PPTX, and images) through the browser.

As shown in the error message, Marp CLI requires any one of Chromium-based browsers like Chrome, Chromium, and Edge to convert Markdown into PDF without setting `CHROME_PATH` env. These are auto-detectable browsers by Marp CLI.

If any of these browsers was not installed and you are using a one of minor Chromium-based browsers such as Vivaldi and Brave, you have to set `CHROME_PATH` because Marp CLI cannot detect it automatically.

**Comment by yhatt** [comment]
> I would be confused though, why is this CLI tool depending on a browser to be installed to convert a text file to a PDF?

You would be able to figure out the essential factor of Markdown conversion in https://www.markdownguide.org/getting-started/#how-does-it-work.

In short, Marp CLI's PDF conversion is internally doing two translations: "Markdown -> HTML", and "HTML -> PDF".

The browser will be used in the step of "HTML -> PDF". All of Chromium-based browsers have [a interface to convert HTML into PDF](https://developers.google.com/web/updates/2017/04/headless-chrome#create_a_pdf), and PDF conversion is depending on it. (This translation is not available in other browser engines like Firefox and Safari)

A one of ideas to reduce your confusion is including the browser into the CLI, but we have not taken that approach becuase an extra Chromium browser will waste your disk space (over 300MB). Using a daily-used browser is a smarter approach for ordinary users.

**Comment by lk16** [comment]
Thanks for your fast reply and explanation.

> A one of ideas to reduce your confusion is including the browser into the CLI 
I assumed the conversion was done using some library to convert markdown into a PDF, without involving a browser.

**Comment by warpedwood** [comment]
Hi, 
Sorry to comment on this closed issue. I tried to set the path using Brave : /home/user/.config/BraveSoftware/Brave-Browser. But I have the following error : 

`Failure to export: [CLIError] Failed converting Markdown. (Failed to launch the browser process! spawn /home/user/.config/BraveSoftware/Brave-Browser EACCES TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md )`

My environment :
Ubuntu 22.04
VS Code 1.70.1
Marp for VS Code 1.5.2

Thanks for the help

**Comment by yhatt** [comment]
@warpedwood Commonly `/home/user/.config/BraveSoftware/Brave-Browser` is a directory for storing the profile data, not executable file of the browser. You can find the correct path of executable binary by running `which brave-browser`. (and I think it would become `/usr/bin/brave-browser`)

**Comment by warpedwood** [comment]
Yes, it works perfectly now. Thank you very much!
