### ISSUE TITLE
images with relative paths are not exported to PDF

### ISSUE THREAD

**Issue by ymollard** [marp-team/marp-cli#393]
### Version of Marp Tool

@marp-team/marp-cli v1.4.0 (w/ @marp-team/marp-core v2.1.1)

### Operating System

Linux

### Environment

- OS version: Ubuntu 20.04.3
- Node.js version (Marpit / Marp Core/ Marp CLI): 14.17.6
- VS Code version (Marp for VS Code): 1.60.1

### How to reproduce

1. Create the md slides document
```
tee test.md <<EOF
---
marp: true

---
# This picture works
![bg left:40% 30%](https://via.placeholder.com/300.png)

---
# This picture with relative path does not 
![bg left:40% 30%](./300.png)
EOF
```

2. Download the picture locally 
```
wget https://via.placeholder.com/300.png
```

3. Output to PDF
```
marp --pdf test.md
```
Òpen the PDF and see that the image with relative path is ignored.
However outputing to HTML works like a charm.

### Expected behavior

Images with relative paths are exported to the PDF output

### Actual behavior

Images with relative paths are ignored in the PDF output

**Comment by yhatt** [comment]
It's a correct behavior as designed, and looks like not a bug. Haven't you read some warnings about local files while exporting PDF? Like this:

```
$ marp --pdf test.md 
[  INFO ] Converting 1 markdown...
[  WARN ] Marp CLI has detected accessing to local file. That is blocked by security reason. Instead we
          recommend using assets uploaded to online. (Or you can use --allow-local-files option if you are
          understood of security risk)
[  INFO ] test.md => test.pdf
```

Local files will not render to PDF by default in Marp CLI, to prevent accessing unexpected local resources by Markdown file. You should opt-in explicitly by `--allow-local-files` option to work relative paths that are pointing local files.

See https://github.com/marp-team/marp-cli#security-about-local-files and https://github.com/marp-team/marp-cli/pull/10#user-content-security.

**Comment by ymollard** [comment]
Oops sorry I had missed that info :(
Problem solved, thank you!

**Comment by ymollard** [comment]
Oops sorry I had missed that info :(
Problem solved, thank you!

**Comment by ymollard** [comment]
Oops sorry I had missed that info :(
Problem solved, thank you!
