### ISSUE TITLE
Improve reliability of connection to Chrome process

### ISSUE THREAD

**Issue by yhatt** [marp-team/marp-cli#395]
Related: marp-team/marp#165, marp-team/marp#198, puppeteer/puppeteer#6258

We have received some reports about the error thrown `Target.setDiscoverTargets` by Puppeteer. We can try to improve making connection to the spawned Chrome.

### Possible workarounds

- If failed making connection with Chrome in `pipe: true` option, we can try to launch Chrome again with `pipe: false` for making connection through WebSocket instead of pipe.

**Comment by amir734jj** [comment]
Any timeline frame for this release? I will be teaching a class in February and I really like to use this feature.

**Comment by yhatt** [comment]
It would be included in the next patch release that will be shipped in a month. A monthly patch for Marp CLI is just delayed now because I'm currently working on Marpit v3 and Marp Core v3.

**Comment by amir734jj** [comment]
Thank you so much for the PR :)
