### ISSUE TITLE
Rendering not consistent

### ISSUE THREAD

**Issue by tonk** [marp-team/marp-cli#403]
### Version of Marp Tool

@marp-team/marp-cli v1.4.2 (w/ @marp-team/marp-core v2.2.0)

### Operating System

Linux

### Environment

- Fedora release 34 
- Marp CLI from binary (Github)

### How to reproduce

1. Create a slidedeck with an own theme that imports a standard theme
2. Start the Marp server with the command below
3. Rendering is completely wrong, just two images and black background
4. Move the theme file out of the `css` directory
5. Move it back, so that re-rendering is triggered
6. Rendering often OK
7. If not: Edit slidedeck, change nothing and write back
8. Rendering often OK

Start command:

```
marp                                            \
        --title='Automation is fun!!'           \
        --author="TonK"                    \
        --no-config                             \
        --allow-local-files                     \
        --watch                                 \
        --server                                \
        --input-dir slides
```

### Expected behavior

Correct display of the slidedeck in one go.
![2021-11-18_12-13-1637234017](https://user-images.githubusercontent.com/390197/142405202-bae1b0b3-8f93-4679-8ab7-7209daac8bf3.png)

### Actual behavior

Rendering is completely wrong

![2021-11-18_12-12-1637233933](https://user-images.githubusercontent.com/390197/142405059-a8702176-bb2d-4fc6-9d92-3355f1ca97da.png)

**Comment by yhatt** [comment]
Marp team cannot solve your problem because of lack resources to confirm what happening in your slides.

Please provide minimal reproducible resources, and more specific steps to reproduce.

**Comment by tonk** [comment]
I have completely stripped it down and nothing seemed to help, until I removed the `fonts` directory from my `slides` directory.

When I have:

```
.
├── engine.js
├── slides
│   ├── css
│   ├── images
│   ├── fonts
```

it doesn't work

If I have

```
.
├── engine.js
├── slides
│   ├── css
│   ├── images
```
it does??

Is it not allowed to have specific fonts?

I can live with it, but would be nice to know why?

Thanks for the support and the awesome software.

**Comment by yhatt** [comment]
I don't know because we cannot guess how your local fonts are used in your slides or custom theme from your explanation.

Did you have checked the error logs outputted in the browser's developer console? If failed something in HTML, the browser may tell something helpfuls.

**Comment by tonk** [comment]
I did, and there is nothing there. But even if I do not use the fonts in the CSS the rendering is wrong. Just for having e.g. FontAwsome in these messes things up.

**Comment by yhatt** [comment]
Close for housekeeping the issue tracker of CLI. If you still have met a trouble in the slide, please ask [Marp discussion forum](https://github.com/marp-team/marp/discussions) for help to our community.
