### ISSUE TITLE
Pkg: Error reading from file

### ISSUE THREAD

**Issue by kvark** [marp-team/marp-cli#407]
I'm trying to package Marp for NixOS here - https://github.com/NixOS/nixpkgs/pull/147311
When running the produced binary, all I get is:
> Pkg: Error reading from file.

This is regardless of any parameters passed to it.
I'm sure there is something I'm doing wrong here, but it would be *really* nice if this error was clearer.

**Comment by yhatt** [comment]
Marp CLI's standalone binary packed by [pkg](https://github.com/vercel/pkg) will fail to run with this error if modified. (e.g. UPX compression: https://github.com/vercel/pkg/issues/1269)
Making this error clearer is responsibility of the upstream library so we cannot do anything.

Please confirm the hash value of an installed binary. For example, SHA256 of `marp` binary in `marp-cli-v1.5.0-linux.tar.gz` should be `ec78524a562daca579c42fb43aa77220cfb61bc3fb52ecde8d180a71e16b25cd`.

**Comment by kvark** [comment]
Interesting! NixOS package has to patch the binary to fix the interpreter, i.e. [patchelf --set-interpreter](https://github.com/NixOS/nixpkgs/pull/147311/files#diff-e71e326319b0bb82b8e638bd00c8235de4b4e3389c1f0224667f720c213e7ec5R22), since the default interpreter path isn't present on NixOS by design.
Filed https://github.com/vercel/pkg/discussions/1429 to get some ideas.

I suppose another option would be to just build Marp from source instead of downloading the release.

**Comment by yhatt** [comment]
> I suppose another option would be to just build Marp from source instead of downloading the release.

Exactly! The standalone binary is not recommended way to install Marp CLI for us because it will limit working architectures.

Homebrew just deals with this approach: https://github.com/Homebrew/homebrew-core/pull/77628 -> https://github.com/Homebrew/homebrew-core/pull/77702
