### ISSUE TITLE
PDF creation fails for latest docker image

### ISSUE THREAD

**Issue by hofbi** [marp-team/marp-cli#411]
### Version of Marp Tool

latest

### Operating System

Other (fill out in the environment field)

### Environment

- Docker: https://hub.docker.com/layers/marpteam/marp-cli/latest/images/sha256-94a641167e6b40aea501c09d84b8db38a8f75267720b22003ac683a8c36f8952?context=explore

### How to reproduce

Using the provided docker command according to the README

docker run --rm --init -v $PWD:/home/marp/app/ -e LANG=$LANG marpteam/marp-cli slide-deck.md --pdf

### Expected behavior

PDF is created

### Actual behavior

PDF creation fails with the following error message:

```shell
[ ERROR ] Failed converting Markdown. (Failed to launch the browser process!
          Error relocating /usr/lib/chromium/chrome: wl_proxy_marshal_flags:
          symbol not found
          
          
          TROUBLESHOOTING:
          https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md
          )
```

### Additional information

v1.5.0 and earlies version work. Bug was introduced with the latest version.

**Comment by yhatt** [comment]
It's under investigation. `latest` tag is pointing to in-development version (`main` branch) for early use. As you mentioned, please try the specific version tag like `v1.5.0` if you want a stable workflow.
