### ISSUE TITLE
Code snippet syntax highlighting

### ISSUE THREAD

**Issue by be-rock** [marp-team/marp-cli#420]
Hi,

Thanks for the great project. I have searched in the readme and other issues and it is still not clear to me how to enable syntax highlighting in code snippets. I have tested this with the `theme: default`.

I would expect this below slidedeck to syntax highlight python in both preview mode `marp --preview ./slides` as well as html export `marp slides/slide.md` but it doesnt happen in either circumstance. 

I tried changing themes to `gaia` and `uncover` and I do see some very subtle syntax highlighting but I would prefer to stick with the `default` theme since the formatting and font sizes seems to be changed pretty dramatically by theme changes.

Am I missing something?

Thanks again.

```
---
marp: false
theme: default
paginate: true
---

# testing

` ` `python
# note that the actual slide.md has the spaces removed from the triple-backticks
print('hello world')
` ` `
```

Version specs:
```
MacOS 11.6

➜  marp --version
@marp-team/marp-cli v1.5.2 (w/ @marp-team/marp-core v2.3.2)
```

**Comment by yhatt** [comment]
We cannot reproduce the disabled syntax highlight from your example. The output HTML has the syntax highlight certainly.

````markdown
---
marp: false
theme: default
paginate: true
---

# testing

```python
print('hello world')
```
````

![](https://user-images.githubusercontent.com/3993388/152285150-7f646b0e-f100-4e25-8d34-85e969565927.png)

Try inspecting the element of code block in your browser.

**Comment by be-rock** [comment]
Hi, thanks for the response. Maybe it is there and just really faint?

Is there a way to tweak those colors to make them more noticeable and reserved words like `print` more pronounced? Note that I am not a web developer with js and css knowledge, just a lover of markdown. 

![image](https://user-images.githubusercontent.com/15165956/152437148-6608e5e2-2f09-466d-bdf1-1b421e6cf828.png)

**Comment by be-rock** [comment]
Actually, I do see the syntax highlighting with other keywords like `def`, `return` and the function name here, which is great! Maybe it's just the color of strings that needs to be tweaked?

![image](https://user-images.githubusercontent.com/15165956/152437855-bbc2f8c1-3670-46e8-8c11-cbeaa906f2ed.png)

Thank you.

**Comment by yhatt** [comment]
Yes. Marp Core v2 default theme is using GitHub Gist color theme for syntax highlight (provided by Highlight.js v10).
https://github.com/highlightjs/highlight.js/blob/0c4cc8a1c3aa373aee06796433c1389e4d2a3a45/src/styles/github-gist.css#L77-L79

To tweak the color scheme, use `<style>` HTML element within Markdown to override `.hljs-string` color. Just insert this snippet to your Markdown, and modify the color code `#ff0000` as you like:

```html
<style>
.hljs-string {
  color: #ff0000 !important;
}
</style>
```

And you can also opt in [Marp Core v3](https://github.com/marp-team/marp-core/releases/tag/v3.0.0) to use in CLI. A using color theme has deleted in the latest Highlight.js v11 so Marp Core v3 takes new color scheme.

```console
$ npm i --save @marp-team/marp-core/next

$ marp --version
@marp-team/marp-cli v1.5.2 (w/ user-installed @marp-team/marp-core v3.0.2)
```

![](https://user-images.githubusercontent.com/3993388/152450660-4ce8733d-67f5-47ba-adc2-d0d571d27748.png)

**Comment by be-rock** [comment]
Wow, what an excellent and thorough response. Thanks a lot for your time and great feedback! I will close out the issue now.
