### ISSUE TITLE
Converting md error

### ISSUE THREAD

**Issue by pcardona34** [marp-team/marp-cli#445]
### Version of Marp Tool

marp-cli v1.7.1 (@marp-team/marp-core v2.4.1)

### Operating System

Linux

### Environment

- OS version: Debian 11.3 (Bullseye) ; Linux raspberrypi 5.15.32-v8+ ; aarch64 GNU/Linux
- Node.js version : v12.22.5
- marp-cli version : @marp-team/marp-cli v1.7.1 (w/ @marp-team/marp-core v2.4.1)

### How to reproduce

1. On a fresh install (new OS : 64 bits)
2. Using this command: `marp --html --allow-local-files --preview foo.md`
3. And trying on many MD files that worked before on my previous OS (32 bits)
4. Always getting this error message now: 
`[  INFO ] Converting 1 markdown...`
`[ ERROR ] Failed converting Markdown. (md.core.ruler.after is not a function)`

### Expected behavior

It should show the preview HTML window on Chromium  like it did before.

### Actual behavior

The error stop the conversion. No HTML, no preview.

**Comment by yhatt** [comment]
Workaround: Try [standalone binary](https://github.com/marp-team/marp-cli/releases) instaed.

It brings from incompatible change with Marp Core in upstream module [markdown-it-emoji v2.0.0 -> 2.0.2](https://github.com/markdown-it/markdown-it-emoji/compare/2.0.0...2.0.2).

**Comment by pcardona34** [comment]
Hi Yhatt,

I did : `sudo npm update @marp-team/marp-cli -g ate`
and every thing is well done now.

Thank you so much for your great work  and this workaround, less than one day to solve it.
Congratulations !
Patrick
