### ISSUE TITLE
National symbols (locale) doesn't handle properly in Windows

### ISSUE THREAD

**Issue by maxx27** [marp-team/marp-cli#465]
### Version of Marp Tool

marp-cli v2.0.4

### Operating System

Windows

### Environment

- OS version: Windows 10.0.19044.1826
- Node.js version (Marpit / Marp Core/ Marp CLI): Node.js 8.15.0
- marp-cli v2.0.4 (w/ marp-core v3.2.1)

### How to reproduce

1. Create any markdown file, e.g. `test.md`:

```markdown
---
marp: true
headingDivider: 3
class: invert
paginate: true
---

test
```

2. In CMD, test regular conversion:

```console
> npx @marp-team/marp-cli -o test.html test.md
[  INFO ] Converting 1 markdown...
[  INFO ] test.md => test.html
```

it works.

3. Let's use non-English characters with Unicode code page:

```console
> chcp 65001
> npx @marp-team/marp-cli -o Löffel.html test.md

Displays and modifies the IP-to-Physical address translation tables used by
address resolution protocol (ARP).
...
```

Not sure whether the issue of my terminal or `npx`.

4. Let's use non-English characters with English default code page:

```console
> chcp 437
> rem German characters
> npx @marp-team/marp-cli -o Löffel.html test.md
[  INFO ] Converting 1 markdown...
[  INFO ] test.md => L├╢ffel.html

> rem Russian characters
>npx @marp-team/marp-cli -o пример.html test.md
[  INFO ] Converting 1 markdown...
[  INFO ] test.md => ╨┐╤Ç╨╕╨╝╨╡╤Ç.html
```

5. If input filename contains such characters, than `marp-cli` can't find it:

```console
> npx @marp-team/marp-cli -o test.html Löffel.html
[  WARN ] Not found processable Markdown file(s).

> npx @marp-team/marp-cli -o проба.html test.md
[  WARN ] Not found processable Markdown file(s).
```

### Expected behavior

Filenames with unicode characters or current locale will be processed correctly:

- output filename will be the same literals as specified in CLI arguments
- marp cli will open/open file with non-English characters in a filename

Right behavior is under Linux (I double checked in WSL).

### Actual behavior

I suppose, marp cli encode provided filenames somehow and it can't read the specified file.

**Comment by yhatt** [comment]
It cannot reproduce in Node.js v18.4.0 and earlier (including LTS). Marp can convert Markdown files correctly even if changed the terminal code page.

But in Node.js v18.5.0 and later, I can confirm the strange behaviors as you explained.

So I guess it is a regression of [Node.js v18.5.0](https://nodejs.org/en/blog/release/v18.5.0/) rather than the bug of Marp. Could you report this to https://github.com/nodejs/node/issues?

**Comment by yhatt** [comment]
I found out it's likely a bug of npm, and report details into npm/cli#5238. It is actually not a bug of Marp so keep track on update of npm.

### Workaround

Downgrade npm to v8.12.x. It's the last version including `npx` not depending on the shell's Windows codepage.

```cmd
npm install -g npm@8.12.2
```

**Comment by yhatt** [comment]
**UPDATE**: npm@8.17.0 and later versions are fixed a bug caused by shell's codepage. (https://github.com/npm/cli/issues/5238#issuecomment-1230552491)
