### ISSUE TITLE
Virus detected (Windows)

### ISSUE THREAD

**Issue by yannmiquel** [marp-team/marp-cli#471]
### Version of Marp Tool

V. 2.1.2 and 2.1.1

### Operating System

Windows

### Environment

- Edge Version 104.0.1293.47

### How to reproduce

Download the file marp-cli-v2.1.*-win.zip

### Expected behavior

No virus

### Actual behavior

Warning of the navigator "Virus detected, unable to download it"

**Comment by yhatt** [comment]
Windows Defender complaints that `Trojan:Script/Wacatac.H!ml` malware was detected. I want to believe it's false positive, based on the result of VirusTotal that says every antivirus softwares did say it's clean.
https://www.virustotal.com/gui/url/32b81192bf007242c9cafb2fe89ed96d4aec3a11831b93e6a93eedbe15b3c3e6/detection

If necessary, try using Node.js to run from source. `npx @marp-team/marp-cli`

> Marp makes standalone packages by using [vercel/pkg](https://github.com/vercel/pkg) and GitHub Actions, and https://github.com/vercel/pkg/issues/1540 is very similar to this case.

**Comment by yannmiquel** [comment]
Thanks for the information

**Comment by yhatt** [comment]
UPDATE: A malware was no longer mis-detected in the latest Windows Defender Definition Update.
