### ISSUE TITLE
Images don't show using CLI, but work fine using VS Code extension

### ISSUE THREAD

**Issue by roland-KA** [marp-team/marp-cli#472]
## Environment:
- Marp CLI 2.1.2 with Marp--Core 3.3.2
- MacOS

## Issue
I embed images using HTML syntax in my markdown files like:
```html
<img src="img/myImage.jpg" alt="myImage" style="zoom: 25%;" />
```

When I generate a HTML-file using the VS Code extension, then everything works well, but when I try to generate a HTML-file using Marp-CLI, then only the text

`<img src="img/myImage.jpg" alt="myImage" style="zoom: 25%;" />`  

appears in the output (instead of the image).

I've tried it with the `--allow-local-files` option, but that doesn't help.

**Comment by roland-KA** [comment]
I have also tried the standard syntax for integrating images like 

`![](img/myImage.jpg)`

... but this leads to the same problem.

**Comment by yhatt** [comment]
Did you try `--html` option to enable raw HTML tags?

**Comment by roland-KA** [comment]
Ah, that works! Now I understand the meaning of this switch.

Thank you very much for the fast answer 😊👍.
