### ISSUE TITLE
 Is there an option to save the markdown.md file as markdown.html without the slides? I want to know how to save markdown as html.

### ISSUE THREAD

**Issue by d10000usd** [marp-team/marp-cli#482]
marp README.md      

The marp mk.md command saves the html the way the slide is inserted.
I want to save markdown without slides. 

There are some times when i simply need to have html without slide.
Thanks for letting me know if you have any options

**Comment by yhatt** [comment]
Marp is designed for Markdown presentation, not Markdown document. You should use the right tool for the right purpose.

- https://adamtheautomator.com/convert-markdown-to-html/
- https://linuxhint.com/convert-markdown-files-linux/

**Comment by d10000usd** [comment]
I am an AI developer. I use a big data document. I am going to give a presentation after the AI ​​summarizes the document. I asked a question because I didn't know what the delay was when marp created the slide. A little bit disappointing to respond.

**Comment by d10000usd** [comment]
> Marp is designed for Markdown presentation, not Markdown document. You should use the right tool for the right purpose.
> 
> * https://adamtheautomator.com/convert-markdown-to-html/
> * https://linuxhint.com/convert-markdown-files-linux/

I am an AI developer. I use a big data document. I am going to give a presentation after the AI ​​summarizes the document. I asked a question because I didn't know what the delay was when marp created the slide. A little bit disappointing to respond.
