### ISSUE TITLE
My images do not render correcly in the PDF

### ISSUE THREAD

**Issue by amineHY** [marp-team/marp-cli#484]
My images do not render correcly in the PDF

```
### Statistiques sur les données

![h:512](images/data_2.png)
```

- PDF file
![image](https://user-images.githubusercontent.com/16307387/201142603-83e80d5e-c68d-400c-9d20-e78083f353cc.png)

- HTML 
![image](https://user-images.githubusercontent.com/16307387/201142888-68d6f0e9-acf2-4a19-aec8-3bbfc2f1c0a7.png)

- Command used : `npx @marp-team/marp-cli@latest slide_marp.md -o output.pdf`

**Comment by yhatt** [comment]
> Transferred the issue from Marp Core to Marp CLI 🚚 

Have you tried `--allow-local-files` option? See this section in the documentation for details:
https://github.com/marp-team/marp-cli#security-about-local-files

**Comment by amineHY** [comment]
Yes, adding --allow-local-files solver the problem
Thank you so much :-)
