### ISSUE TITLE
Support fragment indexing

### ISSUE THREAD

**Issue by pavelzw** [marp-team/marp-cli#495]
### Version of Marp Tool

@marp-team/marp-cli v2.3.0 (w/ @marp-team/marp-core v3.4.2)

### Operating System

macOS

### Environment

- OS version: macOS Ventura 13.1
- Node.js version (Marpit / Marp Core/ Marp CLI): 19.4.0

### How to reproduce

`test.md`
```md
---
marp: true
---

<div data-marpit-fragments="3">
  <div data-marpit-fragment="2">
    two
  </div>
  <div data-marpit-fragment="1">
    one
  </div>
  <div data-marpit-fragment="3">
    three
  </div>
</div>
```

`marp --html -o test.html test.md`

### Expected behavior

```
two <- gets revealed second
one <- gets revealed first
three <- gets revealed third
```

### Actual behavior

```
two <- gets revealed first
one <- gets revealed second
three <- gets revealed third
```

**Comment by pavelzw** [comment]
Related to [maro-team/marpit#264](https://github.com/marp-team/marpit/issues/264).

**Comment by yhatt** [comment]
As described at marp-team/marpit#264, Marp only respects DOM order. (Actually indexes assigned to `data-marpit-fragment` attribute are for another presentation tool made from Marpit framework)

We think it will make confusion that the fragments order is different from visible order, so hints by index number are ignored in Marp. To implement this, [we require clear benefit and strong incentive.](https://github.com/marp-team/.github/blob/master/CONTRIBUTING.md#feature-request)

**Comment by pavelzw** [comment]
In my opinion, it is a bit confusing to support index numbers but then have them ignored by marp-cli. I think that the hybrid solution you mentioned [here](https://github.com/marp-team/marpit/issues/264#issuecomment-735450789) sounds like a good tradeoff.

**Comment by yhatt** [comment]
Close for cleaning up Marp CLI issue tracker. Continue at marp-team/marpit#264 to avoid fragmented discussions at duplicated issues.
