### ISSUE TITLE
Disable emoji in config does not work 

### ISSUE THREAD

**Issue by omundy** [marp-team/marp-cli#497]
How to turn off emoji conversion altogether? I added this to my marp settings in my package.json and it doesn't work to disable emoji conversion.

```json
		"emoji": {
			"shortcode": false,
			"unicode": false
		},
```

![image](https://user-images.githubusercontent.com/279945/212739402-167f9b53-2f2d-4c1a-80c9-68c127917077.png)

Also note issues with these files
![image](https://user-images.githubusercontent.com/279945/212739493-c84acfe7-239d-417d-9cc4-4b94df88bd83.png)

**Comment by yhatt** [comment]
> :truck: Transferred issue from Marp Core to Marp CLI. It's probably a question about Marp CLI configuration. (Recommend to ask in Marp Discussions at first: https://github.com/marp-team/marp/discussions)

To set Marp Core constructor option through Marp CLI configuration interface, you have to put settings into [`options` field](https://github.com/marp-team/marp-cli#example:~:text=Graph%20image%20URL-,options,The%20base%20options%20for%20the%20constructor%20of%20engine,-output).
https://github.com/marp-team/marp-cli#example

An example of `package.json`:

```json
{
  "name": "your-project",
  "private": true,
  "marp": {
    "options": {
      "emoji": {
        "shortcode": false,
        "unicode": false
      }
    }
  }
}
```

> And networking error about `twemoji.maxcdn.com` has already fixed in the latest Marp Core [v3.4.0](https://github.com/marp-team/marp-core/releases/tag/v3.4.0). Try to export again after updating every Marp tools.
>
> Refer and track to twitter/twemoji#580 to know what happening about `twemoji.maxcdn.com`. [MaxCDN has been **permanently** shut down at the end of last year.](https://www.stackpath.com/blog/maxcdn-and-securecdn-are-retiring-heres-what-it-means-for-you)

**Comment by omundy** [comment]
OK thank you for your help. I have finally realized the difference between the ["Options" of the marp-cli](https://github.com/marp-team/marp-cli#options) and [`options` field in the constructor](https://github.com/marp-team/marp-core#constructor-options). Perhaps linking "The base options for the constructor of engine" in the marp-cli ["Options" table](https://github.com/marp-team/marp-cli#options) to the constructor options would be helpful.

**Comment by yhatt** [comment]
> Perhaps linking "The base options for the constructor of engine" in the marp-cli ["Options" table](https://github.com/marp-team/marp-cli#options) to the constructor options would be helpful.

In that context, unfortunately we cannot assert that the constructor options are for Marp Core. [Marp CLI allows the engine to be replaced by another library](https://github.com/marp-team/marp-cli#use-marpit-framework) (e.g. Marpit framework or third-party presentation libraries inherited from Marpit), and `options` may accept different fields from Marp Core.
