### ISSUE TITLE
Docker is sunsetting Free Team organizations

### ISSUE THREAD

**Issue by yhatt** [marp-team/marp-cli#512]
HN: https://news.ycombinator.com/item?id=35154025

Many OSS projects that including us have mentioned about this notification too. We have to consider transferring the host of the Marp CLI official Docker image from Docker Hub into [GitHub Container Registry](https://github.com/features/packages).

## ToDo

- [ ] Update CI workflow for building and publishing Docker image
  - [ ] Consider to move publish workflow to GitHub Actions
- [ ] Announcement
  - The legacy workflow that is depending to `marpteam/marp-cli` would work ~~for a while, but may have a risk of squattings~~.
    - Docker has apologized about this, and described details in https://www.docker.com/blog/we-apologize-we-did-a-terrible-job-announcing-the-end-of-docker-free-teams/.

**Comment by Vad1mo** [comment]
If, for some reason, the Docker-Sponsored Open-Source Program isn't working out, we are happy to help you out. We operate a Harbor-based [container registry as a service ](https://container-registry.com/)that has many benefits over most of the other registries out there.

There are also features regarding containerized image distribution, that might be valuable too as well.

**Comment by yhatt** [comment]
We’re No Longer Sunsetting the Free Team Plan
https://www.docker.com/blog/no-longer-sunsetting-the-free-team-plan/

Docker has decided to keep Free team plan. We need no more extra actions to maintain Marp CLI's official image for now.
