### ISSUE TITLE
[Feature request] marp-cli is-marp <file>

### ISSUE THREAD

**Issue by nopeless** [marp-team/marp-cli#514]
I am using marp to automatically convert marp into html. It would be nice to have a clean way to check whether a markdown file is marp or not. Currently I just check the filename but this feature would be useful

**Comment by yhatt** [comment]
Marp places an emphasis on compatibility with general Markdown files. Therefore, there is no specific specification defining whether a Markdown file is a Marp file or not. It is up to you to distinguish between Markdown and Marp.

However, there may be room for discussion on establishing a standard way in the Marp team's official toolset. ex.:

```
marp "**/*.marp.md"
```

**Comment by nopeless** [comment]
> Marp places an emphasis on compatibility with general Markdown files. Therefore, there is no specific specification defining whether a Markdown file is a Marp file or not. It is up to you to distinguish between Markdown and Marp.
> 
> However, there may be room for discussion on establishing a standard way in the Marp team's official toolset. ex.:
> 
> ```
> marp "**/*.marp.md"
> ```

Currently I detect whether `marp: true` exists. Something like this would be nice

**Comment by MiguelDomingues** [comment]
You can use something like [yq ](https://mikefarah.gitbook.io/yq/) and run the following command:

`yq e --front-matter=extract '. | has("marp")'  the-marp-file-md`

This will output `true` if the `marp` key exists, and `false` otherwise.

Note that the above command is not checking if it is set to true, that can also be done with yq.
If you need to validate the actual value, this could be the solution:

`yq e --front-matter=extract '.marp==true'  the-marp-file-md`

**Comment by nopeless** [comment]
> You can use something like [yq ](https://mikefarah.gitbook.io/yq/) and run the following command:
> 
> `yq e --front-matter=extract '. | has("marp")' the-marp-file-md`
> 
> This will output `true` if the `marp` key exists, and `false` otherwise.
> 
> Note that the above command is not checking if it is set to true, that can also be done with yq. If you need to validate the actual value, this could be the solution:
> 
> `yq e --front-matter=extract '.marp==true' the-marp-file-md`

yes and that is indeed a solution I can use. but doesn't marp already have some kind of functionality that does exactly this? it is a matter of just allowing the cli to invoke it. The only concern that I can forsee is it being too niche or cluttering the documentation. Let me know what you think

**Comment by yhatt** [comment]
> but doesn't marp already have some kind of functionality that does exactly this?

No. `marp: true` is [just a feature only for VS Code extension](https://github.com/marp-team/marp-vscode#usage), not for Marp CLI.

**Comment by nopeless** [comment]
> > but doesn't marp already have some kind of functionality that does exactly this?
> 
> No. `marp: true` is [just a feature only for VS Code extension](https://github.com/marp-team/marp-vscode#usage), not for Marp CLI.
> 
> Related discussion: https://github.com/orgs/marp-team/discussions/301

Ah ok. I am guessing that marp will continue to treat all markdown files equally right?
