### ISSUE TITLE
Fragmented list: each fragment to separate image

### ISSUE THREAD

**Issue by roydekleijn** [marp-team/marp-cli#522]
When having a fragmented list, I expect this will result in separate images if I export it to PNG's.

Is this not possible (yet) or am I missing a setting?

Roy

**Comment by yhatt** [comment]
Duplicated: #141 and #496

Please refer to https://github.com/orgs/marp-team/discussions/311#discussioncomment-2849802 for getting separated images. [Decktape](https://github.com/astefanutti/decktape) can output images by using `--screenshots` option.
