### ISSUE TITLE
[Feature request] Support enabling markdown-it's `typographer` option

### ISSUE THREAD

**Issue by minipli-oss** [marp-team/marp-cli#528]
It would be nice to integrate markdown-it's `typographer` option through a global directive or command line option to get automatic conversions of common markups like (C) → ©, ... → …, -- → &ndash;, etc.

**Comment by yhatt** [comment]
You already can turn on markdown-it's `typographer` option through [a configuration file](https://github.com/marp-team/marp-cli#configuration-file).

```yaml
# .marprc.yml
options:
  markdown:
    typographer: true
```

Marp CLI can customize the constructor option for the engine via `options` field, and its [`markdown` field](https://marpit-api.marp.app/marpit#:~:text=in%20current%20instance.-,markdown,-MarkdownIt%20%7C%20string) (supported by the [Marpit framework](https://github.com/marp-team/marpit), that is the base class of [Marp Core](https://github.com/marp-team/marp-core) engine) can customize markdown-it's constructor options.

**Comment by minipli-oss** [comment]
Indeed, this works! :D I was looking too hard for a way to enable it through the Markdown front matter to not see the (obvious) way of doing it through a configuration file.

Thanks a lot for the detailed answer!
