### ISSUE TITLE
CSS letter-spacing adds extra spaces between letters in PDF

### ISSUE THREAD

**Issue by tsaquet** [marp-team/marp-cli#529]
Hello,

Marp is a great tool, thank you 👍 

I use marp-cli to generate HTML and PDF, I have a theme based on the provided "uncover" theme.

Some people using my PDF files told me about some problems, they are extra spaces between letters, which causes two issues : 
- impossible to use the research tool in the PDF
- copy/paste is quite unsable too

I spent quite a lot of time to investigate to find out that :
- Most of HTML/CSS -> PDF converters have that problem
- It is caused by the "letter-spacing" property in CSS

I added a specific "letter-spacing: unset;" for my PDF generations, it solves the problems above but the result without the spacing is not so good, I would like to keep the spacing without the drawbacks. Til now, I could not find a solution.

Does anyone see a better solution to that problem ?

Thank you !

**Comment by tsaquet** [comment]
I'll provide a minimal example dureing the week, thank you :)

**Comment by yhatt** [comment]
Close for housekeeping. 🧹 This is probably depending on PDF viewer to read, and Marp cannot do anything for that.
