### ISSUE TITLE
The coloring of CLI output is not accessible

### ISSUE THREAD

**Issue by chtenb** [marp-team/marp-cli#552]
![image](https://github.com/marp-team/marp-cli/assets/1030961/2138f2f0-bf04-4fd8-a207-38ef521d8dd6)

In general it's not a good idea to assume that two terminal colors from the terminal color palette make a readable back- and foreground. Instead, it's better to leave the background as is, and only change the foreground, or use the "reverse" modifier, if a highlighting effect is desired.

**Comment by yhatt** [comment]
[v3.3.1](https://github.com/marp-team/marp-cli/releases/tag/v3.3.1) :)
