### ISSUE TITLE
Unable to launch marp if a subdirectory or file is not readable

### ISSUE THREAD

**Issue by lsignac** [marp-team/marp-cli#560]
marp fails if a file is not readable :

```
$ mkdir Test-marp
$ cd Test-marp/
$ touch secret.md
$ chmod a-r secret.md
$ cat<<EOF > slides.md
> ---
> title: Slides
> ---
> 
> # Firest slide
> 
> EOF
$ marp .
[  INFO ] Converting 2 markdowns...
[ ERROR ] Failed converting Markdown. (EACCES: permission denied, open
          'Test-marp/secret.md')
```

Deleting `secret.md` solves the problem.
I think (not sure... ;) ) marp should just ignore unreadable files and should not fail.

**Comment by yhatt** [comment]
Marp CLI has historically been fail fast to avoid passing conversion errors to subsequent processes, such as watch mode, preview mode, etc.

If we were to refactor the multi-file conversion, we would have to make the error scope file by file, and then pass the conversion success/failure for each file to the subsequent process. :)

It would be good to provide `--fail-fast` option too, for users who want the traditional workflow.
