### ISSUE TITLE
Greek characters in path

### ISSUE THREAD

**Issue by nkpap** [marp-team/marp-cli#562]
When using the marp command line, images located in path containing Greek chars are not included in the pdf output.

BR
Nikos

**Comment by yhatt** [comment]
Aren't you missing to add `--allow-local-files` option? Due to the security reason, PDF conversion cannot use local files by default.
https://github.com/marp-team/marp-cli#security-about-local-files

**Comment by nkpap** [comment]
Yes, I do use it. My command is: `marp --html --allow-local-files --pdf-outlines 1-architectures.md -o 1-architectures.pdf` and the working path is of the form: `/home/nik/DATA/Αρχιτεκτονική/LECTURES/`. If moved to a different path with no greek chars it is rendered correctly.

**Comment by nkpap** [comment]
Thank you for responding.
Yes, I am using the option. My full command is `marp --html --allow-local-files --pdf-outlines 1-architectures.md -o 1-architectures.pdf`. 
However I noticed that the problem comes when I run the command on a secondary disk and it is not due to the Greek chars. The path contains a soft link of the second disk. I believe this is the problem.
Thank you 
N.-

**Comment by yhatt** [comment]
OK. Closed as invalid.
