### ISSUE TITLE
[v4] File conversions using Firefox through WebDriver BiDi

### ISSUE THREAD

**Issue by yhatt** [marp-team/marp-cli#565]
### Background

Mozilla and Google have announced that Puppeteer now supports WebDriver BiDi protocol. The headless Firefox could not generate PDF for a long time. But now, Firefox becomes able to generate PDF through WebDriver BiDi (Since Firefox 112: https://bugzil.la/1806810)

The support for other functions Marp CLI is depending is still in progress, but that is well worth to try to support PDF/PPTX/image conversion using Firefox.

Most Linux distributions have installed Firefox as a default browser. If implemented the auto-detection of Firefox binary path, Linux users may no longer have to worry about installed browsers. It's important because Marp ecosystem should be easy to touch for everyone.

#### Related pages

- https://hacks.mozilla.org/2023/12/puppeteer-webdriver-bidi/
- https://developer.chrome.com/blog/puppeteer-webdriver-bidi-2023
- https://pptr.dev/webdriver-bidi

#### Related issues

- https://github.com/marp-team/marp-vscode/issues/370

### Concerns

- Currently Firefox does not support `Page.pdf({ preferCSSPageSize: true })`. Marp CLI conversion logic has to set the proper width and height instead of relying on Marpit's `printable` option.
- Firefox emits only PNG file even if used `page.screenshot` with `type` option as another file type.

**Comment by ErnestoHoro** [comment]
Thank you for this one. I've tried marp for the first time and gave it a quick test, looks promising so far (on a machine with _macOS 14.6.1 / Firefox 128.0_).

Also have Vivaldi installed; I wonder if it complies to the requirements, as a Chromium derivative, and support would be of interest.

**Comment by yhatt** [comment]
@ErnestoHoro Thank you for your early feedback too. The Chromium-flavored browsers such as Vivaldi should be compatible with Marp CLI, and you can test setting the path to Vivaldi as `CHROME_PATH` environment variable.

In v4, I'm going to implement a convenient option `--browser-path`.
