### ISSUE TITLE
Different styling in HTML and PDF

### ISSUE THREAD

**Issue by johnny12150** [marp-team/marp-cli#567]
Is it normal to have different styles in HTML and PDF?

### HTML Outputs
<img width="1696" alt="image" src="https://github.com/marp-team/marp-cli/assets/22369387/224ccd32-30d3-4f90-a714-d48275cf18f4">

<img width="1694" alt="image" src="https://github.com/marp-team/marp-cli/assets/22369387/0be89f7a-a1a4-4c7c-84a8-7bc58e067c8d">

### PDF Outputs
<img width="1455" alt="image" src="https://github.com/marp-team/marp-cli/assets/22369387/4cb05034-c750-4d21-8251-563145f59f17">

<img width="1457" alt="image" src="https://github.com/marp-team/marp-cli/assets/22369387/717c4593-4984-415d-a953-45a57f7bf2ef">

**Comment by yhatt** [comment]
Yes, when the environments used for conversion are different, the fonts displayed in HTML and PDF may differ.

HTML uses the system fonts installed on the viewer's system to display slides. On the other hand, PDF uses the system fonts installed on the system used for conversion.

EXAMPLE: When using [Marp CLI Docker image](https://hub.docker.com/r/marpteam/marp-cli/) in Mac, the Mac's system fonts are used when displaying the output HTML. PDF generation is processed on the Docker image's Linux environment, so the system fonts pre-installed on Linux in the Docker image are used. When using [Marp CLI installed on Mac](https://github.com/marp-team/marp-cli#install), the fonts used for both HTML and PDF should match.

**Comment by johnny12150** [comment]
Thanks for the detailed explanation, since it's a expected behavior, I will close this issue.
