### ISSUE TITLE
marp-cli docker pull rate limited

### ISSUE THREAD

**Issue by ankudinov** [marp-team/marp-cli#577]
I'm facing some random rate limit messages when pulling marp-cli image from internal Gitlab CI (have not seen that when pulling from public Github repo). I'm curious if marp-cli is using free plan on Docker hub? I have definitely seen that causing timeouts for my own container images in the past. Docker Hub rate limiting is [explained here](https://www.docker.com/increase-rate-limits/). If that's the case, are there any plans to more images to GHRC? If not, would you accept a PR for that?

**Comment by yhatt** [comment]
The rate limit is associated to the account of user who tried to pull. The pricing plan of our Docker ID (marpteam) should not matter. 

To avoid pull rate limit error, I recommend to add the login step by `docker login` before pull the Docker image within your CI workflow, or try to use [Dependency Proxy](https://docs.gitlab.com/ee/user/packages/dependency_proxy/#docker-hub-rate-limits-and-the-dependency-proxy) if you are using GitLab.

Even so, the Docker image is providing just for the convenience to try Marp CLI, and I not recommend to use in the workflow. Installing Marp CLI in CI workflow is more reliable way to use It.

https://github.com/orgs/marp-team/discussions/375#discussioncomment-4191221

**Comment by ankudinov** [comment]
There is no rate limit on the non-free org. Anyway that explains the issue.  
Containers much more convenient to build certain pipelines. For example, the link you provided is covering Github Actions, but not Gitlab CI. With the container in use the logic is very portable.  
I'm happy to submit a GH workflow for review to build marp-cli on GHRC (if you are open for that). Github has no rate limit for free or paid accounts. Docker Hub is far from being the best for open source nowadays unfortunately.

**Comment by yhatt** [comment]
Because you asked "I'm curious if marp-cli is using free plan on Docker hub?", I have thought you are misunderstanding as that the pull rate limit for you will become no limit if https://hub.docker.com/u/marpteam became a non-free org.

> the link you provided is covering Github Actions, but not Gitlab CI.

This answer is targeted to GitHub Actions, but the command to run on CI is exactly same: [`npx @marp-team/marp-cli`](https://github.com/marp-team/marp-cli#npx)

Let us continue about publishing the image to the GitHub container registry on another issue #578.

**Comment by xrow** [comment]
I started to remove Docker Inc off my pipelines that is what me brought me here. They seem to be a company without a value nowadays. I guess since github or gitlab have own regsitries keep your stuff there.
