### ISSUE TITLE
laser pointer plugin in server mode

### ISSUE THREAD

**Issue by kpetroff** [marp-team/marp-cli#587]
it would be nice if Marp in server mode would support a "laser pointer" plugin like [reveal.js notes-pointer](https://github.com/djsutherland/reveal.js-notes-pointer).

Is there a way to use reaveal.js plugins in marp server mode?

**Comment by yhatt** [comment]
Marp CLI has not provided reveal.js based template so you cannot use reveal.js plugins, but you can use a laser pointer by tweaking CSS in Markdown or making a Marp plugin.

> ```css
> <style>
> section, section * {
>   cursor: url('data:image/svg+xml,%3Csvg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" height="16" width="16" viewBox="0 0 10 10" %3E%3Ccircle cx="5" cy="5" r="5" fill="red"/%3E%3C/svg%3E '), pointer;
> }
> </style>
> ```
>
> _&mdash; https://github.com/marp-team/marpit/issues/248#issuecomment-629905044_

**Comment by kpetroff** [comment]
wow, thank you for the great answer! That would be fully sufficient for me, thx!
(long term, it would be huge, if the plugin would allow to point in the speaker view, but see the pointer in the presentation window)

**Comment by yhatt** [comment]
We have no plans enhancing current presenter view to keep our implementation simple. If required, please consider to integrate [Marp Core](https://github.com/marp-team/marp-core) with the module, package, or tool that provides the enhanced presenter view.
