### ISSUE TITLE
marp-cli with server and and preview option

### ISSUE THREAD

**Issue by tosaba** [marp-team/marp-cli#60]
On Linux (Ubuntu 18.04.), I am having some problems with the preview mode. Apparently, the program uses `grep` internally, resulting in some unwanted behavior, see CLI output below. 

``` bash
$ marp --server --preview ./MarpTest 
[  INFO ] [Server mode] Start server listened at http://localhost:8080/ ...
[  INFO ] [Preview] (EXPERIMENTAL) Opening http://localhost:8080...
grep: /XXX/XXX/.local/share/applications/zotero.desktop: No such file or directory
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at _errnoException (util.js:1022:11)
    at Pipe.onread (net.js:628:25)
```

During the installation, npm returns the following warning messages
``` bash

/usr/local/bin/marp -> /usr/local/lib/node_modules/@marp-team/marp-cli/marp-cli.js
- arrify@1.0.1 node_modules/@marp-team/marp-cli/node_modules/arrify
- markdown-it-katex node_modules/@marp-team/marp-cli/node_modules/markdown-it-katex
/usr/local/lib
└─┬ @marp-team/marp-cli@0.3.0 
  ├─┬ @marp-team/marp-core@0.5.0 
  │ └─┬ postcss@7.0.14 
  │   └── supports-color@6.1.0 
  ├── @marp-team/marpit@0.6.0 
  ├─┬ chalk@2.4.2
  │ └── supports-color@5.5.0 
  └─┬ globby@9.0.0 
    ├─┬ dir-glob@2.2.2 
    │ └─┬ path-type@3.0.0
    │   └── pify@3.0.0 
    ├── fast-glob@2.2.6 
    ├── ignore@4.0.6 
    ├── pify@4.0.1 
    └── slash@2.0.0 

npm WARN optional Skipping failed optional dependency /@marp-team/marp-cli/chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.2.7
```

**Comment by yhatt** [comment]
Thank you for reporting! But unfortunately, I could not reproduce the reported error.

As far as I know, `grep` command will use for finding executable Chrome from `~/.local/share/applications` to open preview window. 

The reported error is occured caused by `zotero.desktop`. Would you check file permission and whether breaking symbolic link?

```
ls -l ~/.local/share/applications/zotero.desktop
```

**Comment by tosaba** [comment]
Thanks for your answer! It was indeed a broken symbolic link of another (independent) application. However, I wonder why this has any influence on the behavior of marp-cli? 
With having the link fixed, it still returns the same kind of error. As before, it opens a blank window with Marp CLI in the header.

``` bash
$ ls MarpTest/
test.md
$ marp  -p -s ./MarpTest 
[  INFO ] [Server mode] Start server listened at http://localhost:8080/ ...
[  INFO ] [Preview] (EXPERIMENTAL) Opening http://localhost:8080...
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at _errnoException (util.js:1022:11)
    at Pipe.onread (net.js:628:25)
```

I can also confirm that it's related to preview mode as marp-cli works just fine with server-mode only. I can open the address with a browser and click on PDF. 

```bash
$ marp   -s ./MarpTest 
[  INFO ] [Server mode] Start server listened at http://localhost:8080/ ...
[  INFO ] MarpTest/test.md => MarpTest/test.pdf
```

**Comment by tosaba** [comment]
Sorry. Problem solved. You need to have chrome installed. On Ubuntu, chromium is installed by default, which is similar but not the same as chrome.
