### ISSUE TITLE
'npx @marp-team/marp-cli@latest -s ./' hangs

### ISSUE THREAD

**Issue by boldandbusted** [marp-team/marp-cli#609]
Howdy. Thanks for Marpit and marp-cli. I'm excited to try the latest Marpit (version 4.0.0), but I am rewarded with slight sadness. See output log attached. Note that I have to ^Z (background) the process in order to be able to kill it, ctrl-C doesn't work. (I'm on Linux.)

I ran:

```bash
npx -dd --yes @marp-team/marp-cli@latest -s ./
```

Using the same command with @3.4.0 works. Using strace seems to indicate a problem looking up an IP address in Cloudflare's network, but I haven't straced the whole run, just the apparent hang, so don't want to post a confusing log here. I certainly can, if that would be helpful. Cheers.

[npx-out-hang.txt](https://github.com/user-attachments/files/17270950/npx-out-hang.txt)

**Comment by yhatt** [comment]
According to https://github.com/npm/cli/issues/4028, npm 10.4.0 and later may take unexpectedly long time to install due to not responding the request for securiy advisories. The workaround is downgrading npm to v10.3.x.

```
npm install -g npm@~10.3.0
```

I've confirmed mitigated hung up after downgrading.

**Comment by boldandbusted** [comment]
That fixed it! Thank you so much, Yuki! :)

----- Original message -----

**Comment by yhatt** [comment]
The latest npm CLI release [v10.9.1](https://github.com/npm/cli/releases/tag/v10.9.1) seems to be fixed the related problem(s). For those who found this issue: Try to update into the latest npm release.
