### ISSUE TITLE
Running in the Windows command line results in a white box appearing.

### ISSUE THREAD

**Issue by maxin9966** [marp-team/marp-cli#612]
### Version of Marp Tool

2.x or 3.x

### Operating System

Windows

### Environment

- OS version: Windows 10 / Windows 11
- Node.js version Node.js v18.20.2
- marp versions 2.x and 3.x

### How to reproduce

"D:\ai\PyQt-Fluent-Widgets\examples\gallery\dist\AIMediaTools\app\resource\marp.exe" --allow-local-files --images png --theme "C:\Users\ma\AppData\Local\AutoMediaTools\AutoMediaTools\output\style\theme\563f124b4b73e80998559b4b0f47e754.css" -o "C:\Users\ma\AppData\Local\AutoMediaTools\AutoMediaTools\output\video\7f38f028090277d116b932e3b1ed4c57\7f38f028090277d116b932e3b1ed4c57\image_Einstein.png" "C:\Users\ma\AppData\Local\AutoMediaTools\AutoMediaTools\output\video\7f38f028090277d116b932e3b1ed4c57\7f38f028090277d116b932e3b1ed4c57\md_Einstein.md"

### Expected behavior

1

### Actual behavior

Running a command in the Windows command line will result in a white box appearing during the execution of the command, which disappears once the command is complete. This white screen appears in both Windows 10 and Windows 11 PowerShell (built-in on Windows systems), but it does not appear when manually executed in the Anaconda PowerShell Prompt. Versions 2.x and 3.x both exhibit the white screen issue, while version 4.x reports an error when running the test command.

**Comment by yhatt** [comment]
Does this look like similar or related?
https://stackoverflow.com/questions/78996364/chrome-129-headless-shows-blank-window

**Comment by yhatt** [comment]
It should not happen if updated Chrome/Edge to 131 that will be released in next week. That bug is fixed in https://issues.chromium.org/issues/359921643.

It's not that Markdown conversion are failed so Marp CLI has not planned to fix that.
