### ISSUE TITLE
PDF rendering has broken recently

### ISSUE THREAD

**Issue by spkane** [marp-team/marp-cli#73]
I did a little work to narrow this down, but sometime after this commit `3fe441cf7a406416300735b0f5de4a6e48a6ff69` the PDF rendering started hanging (at least in the docker container). Building the Docker container from this commit, still works.

On HEAD, adding `--pdf` to the command line causes the container to just hang while rendering.

```
docker run --rm -v $PWD:/home/marp/app/ marpteam/marp-cli:latest target.md --theme-set spkane.css --pdf --allow-local-files
[  INFO ] Converting 1 markdown...
[  WARN ] Insecure local file accessing is enabled for conversion of target.pdf.
```

Building from an commit about a month or two older results in a working PDF render:

```
docker run --rm -v $PWD:/home/marp/app/ 46c6ff46a3d9 target.md --theme-set spkane.css --pdf --allow-local-files
[  INFO ] Converting 1 markdown...
[  WARN ] Insecure local file accessing is enabled for conversion of target.pdf.
[  INFO ] target.md => target.pdf
```

**Comment by yhatt** [comment]
Hmm, I guess mismatch between supported Chromium version in Marp CLI's [Puppeteer](https://pptr.dev/) and installed Chromium version in Docker image.

```
$ docker run --rm --entrypoint="" marpteam/marp-cli chromium-browser --version
Chromium 71.0.3578.98 
```

[Puppeteer's troubleshooting](https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md#running-on-alpine) says:

> The [newest Chromium package](https://pkgs.alpinelinux.org/package/edge/community/x86_64/chromium) supported on Alpine is 71, which was corresponding to [Puppeteer v1.9.0](https://github.com/GoogleChrome/puppeteer/releases/tag/v1.9.0).

**Comment by yhatt** [comment]
I submitted #74 to fix to use matched Puppeteer version in Docker image. I've confirmed working PDF conversion in built image correctly.

I'll merge it and update `latest` image if it's looks like OK.

**Comment by yhatt** [comment]
Updated Docker image to work PDF conversion. Try running `docker pull marpteam/marp-cli` and converting your PDF again.

**Comment by spkane** [comment]
That appears to have fixed it. Thank you for the quick turnaround!
