### ISSUE TITLE
EACCES: permission denied, open '/home/marp/app/untitled.pdf'

### ISSUE THREAD

**Issue by GreenHatHG** [marp-team/marp-cli#79]
When I try to use it by docker, it gives me an error.
I'd really appreciate it if you could help me with this problem 
![](https://i.loli.net/2019/04/03/5ca3ff3e46c29.png)
![](https://i.loli.net/2019/04/03/5ca3ff840ebd8.png)
`Docker version 18.09.4, build d14af54`

**Comment by yhatt** [comment]
It should doubt permission or owner of directories. (`ls -la | grep ^d`)

It's not the best answer but adding `--privileged` option instead of running with `sudo` might be help you.

**Comment by yhatt** [comment]
We close this issue that has no progress for a week.  Please report more details by executing the presented command if still troubling now.

**Comment by d0ugal** [comment]
I hit the same problem, to work around it I changed the container user. Note `-u "node"` below.

```
docker run -u "node" --rm -v $PWD:/home/marp/app/ -e LANG=$LANG marpteam/marp-cli pres.md --pdf
```

To figure this out I ran the container with a custom entry point to get shell access and see which user had permissions over `/home/marp/app`

```
$  docker run -u "node" -it -v $PWD:/home/marp/app/ -e LANG=$LANG marpteam/marp-cli pres.~/D/F/P/2/secret-life-of-software docker run --entrypoint "sh" -it -v $PWD:/home/marp/app/ -e LANG=$LANG marpteam/marp-cli
~/app $ pwd
/home/marp/app
~/app $ ls -la
total 256
drwxr-xr-x    3 node     node          4096 Jul  2 09:06 .
drwxr-sr-x    1 marp     marp          4096 Jul  2 09:20 ..
-rw-r--r--    1 node     node           857 Jul  1 13:34 notes.txt
-rw-r--r--    1 node     node          3150 Jul  2 09:09 pres.md
```

**Comment by d0ugal** [comment]
> It's not the best answer but adding `--privileged` option instead of running with `sudo` might be help you.

Oh, I forgot to mention in my previous comment that I tried this and it didn't help

**Comment by yhatt** [comment]
If you think Marp CLI's Docker image is assigning `marp` user meaningless, you may send pull request.

https://github.com/marp-team/marp-cli/blob/e79afe29f2e88216ae9832ae78f8ad2c42c2a012/Dockerfile#L25

**Comment by yhatt** [comment]
An useful tips: https://denibertovic.com/posts/handling-permissions-with-docker-volumes/

**Comment by pestophagous** [comment]
I also just encountered this same issue.  Here is another workaround:

```
mkdir directory_anyone_writes_to
cp Downloads/index.md ~/directory_anyone_writes_to/ # put your md file in there
chmod -R 0777 directory_anyone_writes_to/  # grant very loose permission
cd directory_anyone_writes_to/
docker run --rm --init -v $PWD:/home/marp/app/ -e LANG=$LANG marpteam/marp-cli index.md --pdf
```
