### ISSUE TITLE
Marp CLI cannot find a file that name has a pair of brackets

### ISSUE THREAD

**Issue by yhatt** [marp-team/marp-cli#95]
```bash
$ touch "test(1).md"
$ marp "test(1).md" 
[  WARN ] Not found processable Markdown file(s).
...
```

It has reproduced in Windows and macOS. I'm guessing caused by confusion with glob pattern.

**Comment by KyleMit** [comment]
make sure you get your casing right `readme.md` vs `README.md` can be important in build environments like linux

**Comment by yhatt** [comment]
@KyleMit If you have a concern about that, please open new issue instead of taking over a closed issue. FYI following is the current behavior:

- The passed real file path(es) should have been following case sensitivity provided by current file system. e.g. A lot of [linux file systems](https://user-images.githubusercontent.com/3993388/101648055-c7f4d880-3a7c-11eb-8783-738020f8dc73.png) and Mac APFS with case sensitive mode are case sensitive, but [Windows NTFS](https://user-images.githubusercontent.com/3993388/101648096-d2af6d80-3a7c-11eb-9c2a-315f526d32fd.png) and [Mac default APFS](https://user-images.githubusercontent.com/3993388/101648130-dc38d580-3a7c-11eb-9ec0-f305e8c43439.png) are insensitive.
- If recognized the input path as glob pattern, Marp CLI will match glob pattern with enabled case sensitivity  *always*.

**Comment by KyleMit** [comment]
Hey @yhatt , sorry, wasn't trying to dredge up an old issue.  Just trying to leave breadcrumbs for other folks who found this via google like me.  I can remove if it's unhelpful.

Thanks for the library btw - it's been awesome to work with so far

**Comment by yhatt** [comment]
No problem at all! Hope that this information is helpful. 😄
