### ISSUE TITLE
Lose img via marp command

### ISSUE THREAD

**Issue by thehongwu** [marp-team/marp-cli#96]
using following command

`npx @marp-team/marp-cli slides.md -o slides.pdf`

image could be successfully viewed in VS code with following syntax
![img](example.png)

after execute the command above, the pdf shows a img thumbnail instead of the image itself.

like this

![image](https://user-images.githubusercontent.com/11080568/57743003-592d7e80-7691-11e9-8815-c0c9ba3ff1c7.png)

but once you upload you image to some web host, it works, seems the problem here is Marp Cli doesn't support local images

**Comment by yhatt** [comment]
[Please read this section of README.md.](https://github.com/marp-team/marp-cli#security-about-local-files) For security reason (#10), local file access is disabled by default. You have to specify `--allow-local-files` option explicitly.
